#+OPTIONS: toc:nil
# #+LaTeX_CLASS: koma-article 

#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation,aspectratio=169]
#+OPTIONS: H:2

#+LaTex_HEADER: \usepackage{khpreamble}
#+LaTex_HEADER: \usepackage{amssymb}
#+LaTex_HEADER: \usepgfplotslibrary{groupplots}

#+LaTex_HEADER: \newcommand*{\shift}{\operatorname{q}}

#+title: Process Automation Laboratory - Modeling second-order systems
#+date: 2020-08-17

* What do I want the students to understand?			   :noexport:
  - Deviation variables
  - First and second order system modeling

* Which activities will the students do?			   :noexport:
  - Intuition about heat echange
  - Work with deviation variables
  - Assignment


* Repetition - Fitting first-order model with delay
** Fitting first-order model with delay
   Assuming a plant model of first-order with time constant \(T\) and delay \(\theta\)
   \[  \quad \textcolor{green!50!black}{Y(s)} = \frac{K\mathrm{e}^{-s\theta}}{s\tau + 1}\textcolor{blue!80!black}{U(s)} \quad \overset{U(s) = \frac{u_f}{s}}{\Longrightarrow} \quad \textcolor{green!50!black}{y(t)} = u_f K\big( 1 - \mathrm{e}^{-\frac{t-\theta}{\tau}}\big)u_H(t-\theta)\]
   #+begin_export latex
   \def\Tcnst{3}
   \def\tdelay{0.6}
   \def\ggain{2}
   \def\uampl{0.8}
   \pgfmathsetmacro{\yfinal}{\uampl*\ggain}
   \pgfmathsetmacro{\yone}{0.283*\yfinal}
   \pgfmathsetmacro{\ytwo}{0.632*\yfinal}
   \pgfmathsetmacro{\tone}{\tdelay + \Tcnst/3}
   \pgfmathsetmacro{\two}{\tdelay + \Tcnst}

   \begin{center}
     \begin{tikzpicture}
       \begin{axis}[
       width=14cm,
       height=4.5cm,
       grid = both,
       xtick = {0, \tdelay, \tone, \two},
       xticklabels = {0, $\theta$, $\theta+\frac{\tau}{3}$, $\theta + \tau$},
       ytick = {0, \yone, \ytwo, \uampl, \yfinal},
       yticklabels = {0, $0.283y_{f}$, $0.632y_f$, $u_f$, $y_f$},
       xmin = -0.2,
       %minor y tick num=9,
       %minor x tick num=9,
       %every major grid/.style={red, opacity=0.5},
       ]
	 \addplot [thick, green!50!black, no marks, domain=0:10, samples=100] {\uampl*\ggain*(x>\tdelay)*(1 - exp(-(x-\tdelay)/\Tcnst)} node [coordinate, pos=0.9, pin=-90:{$y(t)$}] {};
	 \addplot [const plot, thick, blue!80!black, no marks, domain=-1:10, samples=100] coordinates {(-1,0) (0,0) (0,\uampl) (10,\uampl)} node [coordinate, pos=0.9, pin=-90:{$u(t)$}] {};
       \end{axis}
     \end{tikzpicture}
   \end{center}
   #+end_export

   \[ y_f = \lim_{t\to\infty} y(t) = u_f K \quad \Rightarrow \quad K = \frac{y_f}{u_f}. \]

* Second-order model critically damped
** Second-order models
** Two first-order models in series
   #+begin_export latex
   \begin{center}
   \begin{tikzpicture}
     \node {\includegraphics[width=0.4\linewidth]{../../figures/tank-with-hole-no-variables}};
     \node at (4.35,-1.6) {\includegraphics[width=0.4\linewidth]{../../figures/tank-with-hole-no-variables}};
   \end{tikzpicture}
   \end{center}

   \begin{center}
     \begin{tikzpicture}[node distance=22mm, block/.style={rectangle, draw, minimum width=15mm}, sumnode/.style={circle, draw, inner sep=2pt}]
    
       \node[coordinate] (input) {};
       \node[block, right of=input, node distance=20mm] (plant1)  {$G_1(s)$};
       \node[block, right of=plant1, node distance=26mm] (plant2)  {$G_2(s)$};
       \node[coordinate, right of=plant2, node distance=20mm] (output) {};

       \draw[->] (input) -- node[above, pos=0.3] {$u(t)$} (plant1);
       \draw[->] (plant1) -- node[coordinate, ] (mp) { } (plant2);
       \draw[->] (plant2) -- node[above, near end] {$y(t)$} (output);
       \draw[red] (plant1.south west) ++(-4mm,-10mm) rectangle ++(49mm, 20mm);
       
       \node[red,below of=mp, node distance=10mm] {$G(s) = G_1(s)G_2(s)$};
     \end{tikzpicture}
   \end{center}

   #+end_export



** Fitting second-order critically-damped model
   *Model with two identical time-constants.*
   Assuming model 
   \[ \textcolor{green!50!black}{Y(s)} = \frac{K}{(s\tau + 1)^2}\textcolor{blue!80!black}{U(s)} \quad \overset{U(s) = \frac{u_f}{s}}{\Longrightarrow} \quad \textcolor{green!50!black}{y(t)} = u_f K\Big( 1 - (1+\frac{t}{\tau}\big)\mathrm{e}^{-\frac{t}{\tau}}\Big)u_H(t)\]
   #+begin_export latex
   \def\Tcnst{2}
   \def\tdelay{0.0}
   \def\ggain{2}
   \def\uampl{0.8}
   \pgfmathsetmacro{\yfinal}{\uampl*\ggain}
   \pgfmathsetmacro{\ytwo}{\yfinal*(1-2*exp(-1))}
   \pgfmathsetmacro{\two}{\tdelay + \Tcnst}

   \begin{center}
     \begin{tikzpicture}
       \begin{axis}[
       width=14cm,
       height=4.5cm,
       grid = both,
       xtick = {0, \two},
       xticklabels = {0,  $\tau$},
       ytick = {0, \ytwo, \uampl, \yfinal},
       yticklabels = {0, $ $, $u_f$, $y_f$},
       xmin = -0.2,
       clip = false,
       %minor y tick num=9,
       %minor x tick num=9,
       %every major grid/.style={red, opacity=0.5},
       ]
	 \addplot [thick, green!50!black, no marks, domain=0:11, samples=100] {\uampl*\ggain*(x>\tdelay)*(1 - (1+x/\Tcnst)*exp(-(x-\tdelay)/\Tcnst)} node [coordinate, pos=0.9, pin=-90:{$y(t)$}] {};
	 \addplot [const plot, thick, blue!80!black, no marks, domain=-1:11, samples=100] coordinates {(-1,0) (0,0) (0,\uampl) (11,\uampl)} node [coordinate, pos=0.9, pin=-90:{$u(t)$}] {};
	 \node at (axis cs: 11, -0.3) {$t$};
       \end{axis}
     \end{tikzpicture}
   \end{center}
   #+end_export

   *Individual activity* Evaluate the response $y(t)$ at the time instants $t=\tau$!


** Fitting second-order critically-damped model
   *Model with two identical time-constants.*
   Assuming model 
   \[ \textcolor{green!50!black}{Y(s)} = \frac{K}{(s\tau + 1)^2}\textcolor{blue!80!black}{U(s)} \quad \overset{U(s) = \frac{u_f}{s}}{\Longrightarrow} \quad \textcolor{green!50!black}{y(t)} = u_f K\Big( 1 - (1+\frac{t}{\tau}\big)\mathrm{e}^{-\frac{t}{\tau}}\Big)u_H(t)\]
   #+begin_export latex
   \def\Tcnst{2}
   \def\tdelay{0.0}
   \def\ggain{2}
   \def\uampl{0.8}
   \pgfmathsetmacro{\yfinal}{\uampl*\ggain}
   \pgfmathsetmacro{\ytwo}{\yfinal*(1-2*exp(-1))}
   \pgfmathsetmacro{\ytwofactor}{(1-2*exp(-1))}
   \pgfmathsetmacro{\two}{\tdelay + \Tcnst}

   \begin{center}
     \begin{tikzpicture}
       \begin{axis}[
       width=14cm,
       height=4.5cm,
       grid = both,
       xtick = {0, \two},
       xticklabels = {0,  $\tau$},
       ytick = {0, \ytwo, \uampl, \yfinal},
       yticklabels = {0, $\ytwofactor y_f$, $u_f$, $y_f$},
       xmin = -0.2,
       clip = false,
       %minor y tick num=9,
       %minor x tick num=9,
       %every major grid/.style={red, opacity=0.5},
       ]
	 \addplot [thick, green!50!black, no marks, domain=0:11, samples=100] {\uampl*\ggain*(x>\tdelay)*(1 - (1+x/\Tcnst)*exp(-(x-\tdelay)/\Tcnst)} node [coordinate, pos=0.9, pin=-90:{$y(t)$}] {};
	 \addplot [const plot, thick, blue!80!black, no marks, domain=-1:11, samples=100] coordinates {(-1,0) (0,0) (0,\uampl) (11,\uampl)} node [coordinate, pos=0.9, pin=-90:{$u(t)$}] {};
	 \node at (axis cs: 11, -0.3) {$t$};
       \end{axis}
     \end{tikzpicture}
   \end{center}
   #+end_export

   \[ y_f = \lim_{t\to\infty} y(t) = u_f K \quad \Rightarrow \quad K = \frac{y_f}{u_f}. \]

* Second-order model under-damped

** Second-order under-damped models
A system with ODE
$$ \ddot{y} + 2\zeta\omega_n\dot{y} + \omega_n^2 y = \omega_n^2 u, $$
becomes in the Laplace domain
$$ Y(s) = \frac{\omega_n^2}{s^2 + 2\zeta\omega_n s + \omega_n^2} U(s). $$
*** Text
    :PROPERTIES:
    :beamer_col: 0.4
    :END:

- *\(\zeta\)* is called the /damping ratio/.
- *\(\omega_n\)* is called the /natural frequency/ (of the system).

*** Graphics
    :PROPERTIES:
    :beamer_col: 0.6
    :END:
\begin{center}
    \includegraphics[width=4cm]{../../figures/implane-second-order-poles}
\end{center}

** Second-order under-damped models
$$ Y(s) = \frac{\omega_n^2}{s^2 + 2\zeta\omega_n s + \omega_n^2} U(s), \qquad \overset{U(s) = \frac{u_f}{s}}{\Longrightarrow} $$
$$     y(t) = 1 - \frac{\mathrm{e}^{-\zeta\omega_nt}}{\sqrt{1-\zeta^2}} \sin\big( \sqrt{1-\zeta^2}\omega_n t + \phi \big) $$


*** poles
    :PROPERTIES:
    :beamer_col: 0.3
    :END:

\begin{center}
    \includegraphics[width=4cm]{../../figures/implane-second-order-poles}
\end{center}

*** response
    :PROPERTIES:
    :beamer_col: 0.7
    :END:

\begin{center}
    \includegraphics[width=8cm]{../../figures/step-response-specifications}
\end{center}

** Second-order under-damped models
*** poles
    :PROPERTIES:
    :beamer_col: 0.3
    :END:

\begin{center}
    \includegraphics[width=4cm]{../../figures/implane-second-order-poles}
\end{center}

\[    t_r \approx \frac{\pi}{2\omega_n}, \qquad   t_s \approx \frac{4}{\zeta\omega_n}, \]
*** response
    :PROPERTIES:
    :beamer_col: 0.7
    :END:

\begin{center}
    \includegraphics[width=8cm]{../../figures/step-response-specifications}
\end{center}

\[    t_p \approx \frac{\pi}{\sqrt{1 - \zeta^2}\omega_n}, \qquad    \zeta \approx \sqrt{\frac{(\ln \frac{PO}{100})^2}{\pi^2 + (\ln \frac{PO}{100})^2}} \]

** Second-order under-damped models
*Activity in pairs* Determine the poles of the system!
*** poles
    :PROPERTIES:
    :beamer_col: 0.3
    :END:

\begin{center}
    \includegraphics[width=4cm]{../../figures/implane-second-order-poles}
\end{center}

\[    t_s \approx \frac{4}{\zeta\omega_n}, \]
*** response
    :PROPERTIES:
    :beamer_col: 0.7
    :END:


\begin{center}
\begin{tikzpicture}
   \node[anchor=south west] {    \includegraphics[width=8cm]{../../figures/step-response-specifications}};
   \draw[red] (2.2,4.2) -- ++(-1.2,0) node[left] {$1.3 y_f$};
   \draw[red, dotted] (3.7,0.8) -- ++(0,-0.3) node[below] {$2$};

\end{tikzpicture}
\end{center}

\[   \zeta \approx \sqrt{\frac{(\ln \frac{PO}{100})^2}{\pi^2 + (\ln \frac{PO}{100})^2}} \]

* First-order model exercise                                       :noexport:
** First-order model with delay - exercise
   *Activity* In groups of two: Share screen with this slide. Note \(y_f\), \(0.632y_f\), \(0.283y_f\), \(u_f\), \(t_1\) y \(t_2\). Determine the parameters of the first-order model with delay.

   #+begin_export latex
   \def\uampl{0.5}
   \def\ttdelay{0.3}
   \def\TTcnst{1.6}
   \def\ggain{3}

   \pgfmathsetmacro{\yfinal}{\uampl*\ggain}
   \pgfmathsetmacro{\yone}{0.283*\yfinal}
   \pgfmathsetmacro{\ytwo}{0.632*\yfinal}
   \pgfmathsetmacro{\tone}{\tdelay + \Tcnst/3}
   \pgfmathsetmacro{\two}{\tdelay + \Tcnst}


   \begin{center}
     \begin{tikzpicture}
       \begin{axis}[
       width=13cm,
       height=6cm,
       grid = both,
       minor y tick num=9,
       minor x tick num=9,
       every major grid/.style={red, opacity=0.5},
       xlabel = {$t$},
       xmin = -1,
       ]
	 \addplot [thick, green!50!black, no marks, domain=0:10, smooth, samples=16] {\uampl*\ggain*(x>\ttdelay)*(1 - (1+(x-\ttdelay)/\TTcnst)*exp(-(x-\ttdelay)/\TTcnst))} node [coordinate, pos=0.9, pin=-90:{$y(t)$}] {};
	 \addplot [const plot, thick, blue!80!black, no marks, domain=-1:10, samples=100] coordinates {(-1,0) (0,0) (0,\uampl) (10,\uampl)} node [coordinate, pos=0.9, pin=-90:{$u(t)$}] {};
       \end{axis}
     \end{tikzpicture}
   \end{center}
   #+end_export

** First-order model with delay - Solution
** First-order model with delay - Solution

   #+begin_export latex
   \def\uampl{0.5}
   \def\ttdelay{0.3}
   \def\TTcnst{1.6}
   \def\ggain{3}
   \def\tdelay{1.125} % Resulting from method
   \def\Tcnst{2.625} % Resulting from method

   \pgfmathsetmacro{\yfinal}{\uampl*\ggain}
   \pgfmathsetmacro{\yone}{0.283*\yfinal}
   \pgfmathsetmacro{\ytwo}{0.632*\yfinal}
   \pgfmathsetmacro{\tone}{2}
   \pgfmathsetmacro{\two}{3.75}


   \begin{center}
     \begin{tikzpicture}
       \begin{axis}[
       width=12cm,
       height=5cm,
       grid = both,
       minor y tick num=9,
       minor x tick num=9,
       every major grid/.style={red, opacity=0.5},
       xlabel = {$t$},
       xmin = -1,
       clip=false,
       ]
	 \addplot [thick, green!50!black, no marks, domain=0:10, smooth, samples=16] {\uampl*\ggain*(x>\ttdelay)*(1 - (1+(x-\ttdelay)/\TTcnst)*exp(-(x-\ttdelay)/\TTcnst))} node [coordinate, pos=0.9, pin=-90:{$y(t)$}] {};
	 \addplot [const plot, thick, blue!80!black, no marks, domain=-1:10, samples=100] coordinates {(-1,0) (0,0) (0,\uampl) (10,\uampl)} node [coordinate, pos=0.9, pin=-90:{$u(t)$}] {};
	 \draw[thick, red, dashed] (axis cs: \tone, \yone) -- (axis cs: \tone, -0.45) node[below] {$t_1 = \tone = \tau + \frac{\tau}{3}$}; 
	 \draw[thick, red, dashed] (axis cs: \tone, \yone) -- (axis cs: -2,\yone) node[left, anchor=east] {$0.283y_f = \yone$}; 
	 \draw[thick, orange, dashed] (axis cs: \two, \ytwo) -- (axis cs: \two, -0.9) node[below] {$t_2 = \two = \tau + \tau$}; 
	 \draw[thick, orange, dashed] (axis cs: \two, \ytwo) -- (axis cs: -2, \ytwo, -0.9) node[left, anchor=east] {$0.632y_f = \ytwo$}; 
	 \draw[thick, green!60!black, dashed] (axis cs: 10, \yfinal) -- (axis cs: -2, \yfinal) node[left, anchor=east] {$y_f = \yfinal$}; 
	 \draw[blue!70!black, dashed] (axis cs: 10, \uampl) -- (axis cs: 10.2, \uampl, -0.9) node[above] {$u_f = \uampl$}; 

       \end{axis}
     \end{tikzpicture}
   \end{center}
   #+end_export
   \[ \begin{cases} \tone = \tau + \frac{\tau}{3}\\ \two = \tau + \tau \end{cases} \quad \Rightarrow \quad \begin{cases} \tau = 1.125 \\ T = 2.625 \end{cases}, \qquad  K = \frac{y_f}{u_f} = \frac{\yfinal}{\uampl} = \ggain \]
** First-order model with delay - Solution
   #+begin_export latex
   \def\uampl{0.5}
   \def\ttdelay{0.3}
   \def\TTcnst{1.6}
   \def\ggain{3}
   \def\tdelay{1.125} % Resulting from method
   \def\Tcnst{2.625} % Resulting from method

   \pgfmathsetmacro{\yfinal}{\uampl*\ggain}
   \pgfmathsetmacro{\yone}{0.283*\yfinal}
   \pgfmathsetmacro{\ytwo}{0.632*\yfinal}
   \pgfmathsetmacro{\tone}{2}
   \pgfmathsetmacro{\two}{3.75}


   \begin{center}
     \begin{tikzpicture}
       \begin{axis}[
       width=12cm,
       height=5.5cm,
       grid = both,
       minor y tick num=9,
       minor x tick num=9,
       every major grid/.style={red, opacity=0.5},
       xlabel = {$t$},
       xmin = -1,
       clip=false,
       ]
	 \addplot [thick, green!50!black, no marks, domain=0:10, smooth, samples=16] {\uampl*\ggain*(x>\ttdelay)*(1 - (1+(x-\ttdelay)/\TTcnst)*exp(-(x-\ttdelay)/\TTcnst))} node [coordinate, pos=0.9, pin=-90:{$y(t)$}] {};
	 \addplot [const plot, thick, blue!80!black, no marks, domain=-1:10, samples=100] coordinates {(-1,0) (0,0) (0,\uampl) (10,\uampl)} node [coordinate, pos=0.9, pin=-90:{$u(t)$}] {};
	 \addplot [thick, olive!80!black, smooth, no marks, domain=0:10, samples=100] {\uampl*\ggain*(x>\tdelay)*(1 - exp(-(x-\tdelay)/\Tcnst)} node [coordinate, pos=0.6, pin=-90:{model}] {};
	 \draw[thick, red, dashed] (axis cs: \tone, \yone) -- (axis cs: \tone, -0.45) node[below] {$t_1 = \tone = \tau + \frac{\tau}{3}$}; 
	 \draw[thick, red, dashed] (axis cs: \tone, \yone) -- (axis cs: -2,\yone) node[left, anchor=east] {$0.283y_f = \yone$}; 
	 \draw[thick, orange, dashed] (axis cs: \two, \ytwo) -- (axis cs: \two, -0.9) node[below] {$t_2 = \two = \tau + \tau$}; 
	 \draw[thick, orange, dashed] (axis cs: \two, \ytwo) -- (axis cs: -2, \ytwo, -0.9) node[left, anchor=east] {$0.632y_f = \ytwo$}; 
	 \draw[thick, green!60!black, dashed] (axis cs: 10, \yfinal) -- (axis cs: -2, \yfinal) node[left, anchor=east] {$y_f = \yfinal$}; 
	 \draw[blue!70!black, dashed] (axis cs: 10, \uampl) -- (axis cs: 10.2, \uampl, -0.9) node[above] {$u_f = \uampl$}; 

       \end{axis}
     \end{tikzpicture}
   \end{center}
   #+end_export


   \[ \text{\textcolor{olive}{Model:}} \qquad  \textcolor{olive}{G(s) = \ggain \frac{\mathrm{e}^{-\tdelay s}}{\Tcnst s + 1}} \]



