#+OPTIONS: toc:nil
# #+LaTeX_CLASS: koma-article 

#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation,aspectratio=169, usenames, dvipsnames]
#+OPTIONS: H:2

#+LaTex_HEADER: \usepackage{khpreamble}
#+LaTex_HEADER: \usepackage{amssymb}
#+LaTex_HEADER: \usepgfplotslibrary{groupplots}
#+LaTex_HEADER: \usepackage{pgfplotstable}

#+LaTex_HEADER: \newcommand*{\shift}{\operatorname{q}}
#+LaTex_HEADER:   \definecolor{ppc}{rgb}{0.1,0.1,0.6}
#+LaTex_HEADER:   \definecolor{iic}{rgb}{0.6,0.1,0.1}
#+LaTex_HEADER:   \definecolor{ddc}{rgb}{0.1,0.6,0.1}



#+title: Process Automation Laboratory - Anti windup
#+date: 2020-09-21

* What do I want the students to understand?			   :noexport:
  - Saturation problem
  - Windup
  - Anti-windup schemes

* Which activities will the students do?			   :noexport:
  - Intuition about windup
  - Implement ant-windup

* Context
** Two -tank model
   #+begin_export latex
   \begin{center}
   \includegraphics[width=\linewidth]{../../figures/two-tanks-shutoff-valve}
   \end{center}
   #+end_export

* Repetition PID
** Feedback control
   #+begin_export latex
   \begin{center}
   \begin{tikzpicture}[node distance=22mm, block/.style={rectangle, draw, minimum width=15mm}, sumnode/.style={circle, draw, inner sep=2pt}]
  { 
  \node[coordinate] (input) {};
  \node[sumnode, right of=input] (sum) {\tiny $\sum$};
  \node[block, right of=sum, node distance=2.6cm] (reg) {$F(s)$};
  \node[block, right of=reg, node distance=2.6cm] (plant) {$G(s)$};
  \node[coordinate, right of=plant, node distance=2cm] (output) {};
  \node[coordinate, below of=plant, node distance=12mm] (feedback) {};
 
  \draw[->] (plant) -- node[coordinate, inner sep=0pt] (meas) {} node[near end, above] {$y(t)$} (output);
  \draw[->] (meas) |- (feedback) -| node[very near end, left] {$-$} (sum);
  \draw[->] (input) -- node[very near start, above] {$r(t)$} (sum);
  \draw[->] (sum) -- node[above] {$e(t)$} (reg);
  \draw[->] (reg) -- node[above] {$u(t)$}(plant);
}
\end{tikzpicture}
\end{center}
   #+end_export

   

** The PID - practical form
   \definecolor{ppc}{rgb}{0.1,0.1,0.6}
   \definecolor{iic}{rgb}{0.6,0.1,0.1}
   \definecolor{ddc}{rgb}{0.1,0.5,0.1}
   
   #+begin_export latex
   \begin{center}
     \begin{tikzpicture}[node distance=22mm, block/.style={rectangle, draw, minimum width=15mm}, sumnode/.style={circle, draw, inner sep=2pt}]
    
       \node[coordinate] (input) {};
       \node[sumnode, right of=input, node distance=16mm] (sum) {\tiny $\Sigma$};
       \node[color=iic,block, right of=sum, node distance=28mm] (ii)  {$\frac{1}{\tau_is}$};
       \node[color=ppc, coordinate, above of=ii, node distance=10mm] (pp)  {};
       \node[color=ddc,block, below of=ii, node distance=13mm] (dd)  {$\frac{\tau_ds}{\frac{\tau_d}{N}s + 1}$};
       \node[sumnode, right of=ii, node distance=20mm] (sum2) {\tiny $\Sigma$};
       \node[block, right of=sum2, node distance=20mm] (gain)  {$k_c$};
       \node[coordinate, below of=sum, node distance=12mm] (feedback) {};
       \node[coordinate, right of=gain, node distance=20mm] (output) {};

       \draw[->] (input) -- node[above, pos=0.3] {$r(t)$} (sum);
       \draw[->] (sum) -- node[above, pos=0.2] {$e(t)$} node[coordinate] (mm) {}  (ii);
       \draw[->] (gain) -- node[above, near end] {$u(t)$} (output);
       \draw[->] (feedback) -- node[left, near start] {$y(t)$} node[right, pos=0.95] {-} (sum);
       \draw[->, color=ppc] (mm) |- (pp) -| node[right,] {$u_P(t)$} (sum2);
       \draw[->, color=ddc] (feedback |- dd) -- node[above, pos=0.95] {-} (dd);
       \draw[->, color=ddc] (dd) -| node[right,] {$u_D(t)$} (sum2)  ;
       \draw[->, color=iic] (ii)  -- node[above,] {$u_I(t)$} (sum2);
       \draw[->] (sum2) -- node[above, near end] {} (gain);

     \end{tikzpicture}
   \end{center}
   #+end_export

   The parameter \(N\) is chosen to limit the influence of noisy measurements. Typically,
   \[  3 < N < 20 \]

** The PID - practical aspects

   #+begin_export latex
   {\footnotesize Åström \& Hägglund (1988) \emph{PID controllers: Theory, design and tuning, 2nd ed} Instrument Society of America.}
   #+end_export

*** Approximating nonlinear systems with linear models
    - Model is accurate only in neighborhood of operating point for which system is approximated.
    - Solution: Divide operating range into many regions, with separate PID parameters for each region
    
*** Approximating high-order systems with low-order models
    - Only accurate for low frequencies
    - Beware of behavior for high-frequency input to the closed-loop system

** The PID - practical aspects, contd
*** When do PID controllers work well?
    - The plant dynamics can be well approximated with low-order model
    - Demands on performance not too high
*** More sophisticated control needed when
    - Higher order dynamics
    - Oscillatory modes
    - Long deadtime
    
** The PID - practical aspects, contd
*** Choice of controller

    1. P-controller if damping and steady-state error satisfied
    2. PI-controller if steady-state error must be zero (often 1st order dynamics)
    3. PID-controller if PI does not give sufficient damping (often 2nd order dynamics)
    4. Tuning parameter \(\tau_c\) for SIMC tuning method: 
       - Smaller (=faster) than \(\tau\) if sufficiently damped and limitations on input signal not violated.
       - larger (=slower) than \(\tau\) if more damping required or smaller input signal required.


** The PID - Parallel form, solution
     \(  u(t) = k_c\Big( \textcolor{ppc}{e(t)} + \textcolor{iic}{\overbrace{\frac{1}{\tau_i} \int_0^{t} e(\xi) d\xi}^{u_I(t)}} + \textcolor{ddc}{ \underbrace{\tau_d \frac{d}{dt} \big(-y(t)\big)}_{u_D(t)}} \Big)\)
   #+begin_export latex
      \begin{center}
      \def\TT{1}
      \begin{tikzpicture}
      \begin{axis}[
       clip=false,
       width=14cm,
       height=5cm,
       ylabel={},
       xlabel={$t$},
       ymax = 2,
       ]
	 \addplot[black, no marks, domain=-0.1:8, samples=200] {(x>0)*(1 - (1+x/\TT)*exp(-x/\TT)} node[coordinate, pin=-20:{$y(t)$}, pos=0.4] {};
	 \addplot[magenta!70!black, no marks, domain=-0.1:8, samples=200] coordinates {(-0.1, 0) (0,0) (0,1) (8,1)} node[coordinate, pin=90:{$r(t)$}, pos=0.21] {};
	 \addplot[color=ppc, no marks, domain=0:8, samples=200] {(x>=0)*( (1+x/\TT)*exp(-x/\TT)} node[coordinate, pin=20:{$e(t)$}, pos=0.7] {};
	 \addplot[color=iic, no marks, domain=-0.1:8, samples=200] {(x>0)*(2*(1-exp(-x/\TT)) - \x/\TT*exp(-x/\TT))} node[coordinate, pin=-20:{$u_I(t)$}, pos=0.6] {};
	 \addplot[color=ddc, no marks, domain=-0.1:8, samples=200] {(x>0)*(-\x/\TT*exp(-x/\TT))} node[coordinate, pin=-20:{$u_D(t)$}, pos=0.4] {};
       \end{axis}

    \end{tikzpicture}
   \end{center}
   #+end_export

** The PID - Integral signal
   #+begin_export latex
   \begin{center}
     \begin{tikzpicture}[node distance=22mm, block/.style={rectangle, draw, minimum width=15mm}, sumnode/.style={circle, draw, inner sep=2pt}, scale=0.6, every node/.style={scale=0.6}]
    
       \node[coordinate] (input) {};
       \node[sumnode, right of=input, node distance=16mm] (sum) {\tiny $\Sigma$};
       \node[color=iic,block, right of=sum, node distance=28mm] (ii)  {$\frac{1}{\tau_is}$};
       \node[color=ppc, coordinate, above of=ii, node distance=10mm] (pp)  {};
       \node[color=ddc,block, below of=ii, node distance=10mm] (dd)  {$\tau_ds$};
       \node[sumnode, right of=ii, node distance=20mm] (sum2) {\tiny $\Sigma$};
       \node[block, right of=sum2, node distance=20mm] (gain)  {$k_c$};
       \node[coordinate, below of=sum, node distance=12mm] (feedback) {};
       \node[coordinate, right of=gain, node distance=20mm] (output) {};

       \draw[->] (input) -- node[above, pos=0.3] {$r(t)$} (sum);
       \draw[->] (sum) -- node[above, pos=0.2] {$e(t)$} node[coordinate] (mm) {}  (ii);
       \draw[->] (gain) -- node[above, near end] {$u(t)$} (output);
       \draw[->] (feedback) -- node[left, near start] {$y(t)$} node[right, pos=0.95] {-} (sum);
       \draw[->, color=ppc] (mm) |- (pp) -| node[right,] {$u_P(t)$} (sum2);
       \draw[->, color=ddc] (feedback |- dd) -- node[above, pos=0.95] {-} (dd) -| node[right,] {$u_D(t)$}   (sum2);
       \draw[->, color=iic] (ii)  -- node[above,] {$u_I(t)$} (sum2);
       \draw[->] (sum2) -- node[above, near end] {} (gain);

     \end{tikzpicture}
     \small
     \(  u(t) = k_c\Big( \textcolor{ppc}{e(t)} + \textcolor{iic}{\overbrace{\frac{1}{\tau_i} \int_0^{t} e(\xi) d\xi}^{u_I(t)}} + \textcolor{ddc}{ \underbrace{\tau_d \frac{d}{dt} \big(-y(t)\big)}_{u_D(t)}} \Big)\)
   \end{center}
   #+end_export

   #+begin_export latex
      \begin{center}
      \def\wn{2}
      \def\zz{0.3}
      \pgfmathsetmacro{\wwd}{\wn*sqrt(1-\zz*\zz)}
      \pgfmathsetmacro{\zwn}{\zz*\wn}
     \pgfmathsetmacro{\thangle}{acos(\zz)}
      \begin{tikzpicture}
      \begin{axis}[
       clip=false,
       width=14cm,
       height=4.5cm,
       ylabel={},
       xlabel={$t$},
       ymax = 2,
       ymin = -0.5,
       ]
	 \addplot[black, no marks, domain=-0.4:8, samples=200] {(x>0)*(1 - exp(-x * \zwn)/sqrt(1-\zz*\zz) * sin(deg(\wwd*x) + \thangle))} node[coordinate, pin=20:{$y(t)$}, pos=0.3] {};
	 \addplot[magenta!70!black, no marks, domain=-0.4:8, samples=200] coordinates {(-0.4, 0) (0,0) (0,1) (8,1)} node[coordinate, pin=90:{$r(t)$}, pos=0.2] {};
       \end{axis}

    \end{tikzpicture}
   \end{center}
   #+end_export
 
  *Activity* Sketch the error signal \(e(t)\) and the integral signal \(u_I(t)\) (use \(\tau_i=1\))

** The PID - Integral signal - Solution


   #+begin_export latex
      \def\wn{2}
      \def\zz{0.3}
      \pgfmathsetmacro{\wwd}{\wn*sqrt(1-\zz*\zz)}
      \pgfmathsetmacro{\zwn}{\zz*\wn}
     \pgfmathsetmacro{\thangle}{acos(\zz)}
   \pgfplotstablenew[ create on use/x/.style={ create col/expr={\pgfplotstablerow/50} },    create on use/y/.style={ create col/expr={ exp(-\thisrow{x} * \zwn)/sqrt(1-\zz*\zz) * sin(deg(\wwd*\thisrow{x}) + \thangle)} }, create on use/int/.style={       create col/expr={\pgfmathaccuma+(\thisrow{y}+\prevrow{y})/2*(\thisrow{x}-\prevrow{x})} }, columns={x,y,int}]{400} \pidtable



   \begin{center}
     \begin{tikzpicture}[node distance=22mm, block/.style={rectangle, draw, minimum width=15mm}, sumnode/.style={circle, draw, inner sep=2pt}, scale=0.6, every node/.style={scale=0.6}]
    
       \node[coordinate] (input) {};
       \node[sumnode, right of=input, node distance=16mm] (sum) {\tiny $\Sigma$};
       \node[color=iic,block, right of=sum, node distance=28mm] (ii)  {$\frac{1}{\tau_is}$};
       \node[color=ppc, coordinate, above of=ii, node distance=10mm] (pp)  {};
       \node[color=ddc,block, below of=ii, node distance=10mm] (dd)  {$\tau_ds$};
       \node[sumnode, right of=ii, node distance=20mm] (sum2) {\tiny $\Sigma$};
       \node[block, right of=sum2, node distance=20mm] (gain)  {$k_c$};
       \node[coordinate, below of=sum, node distance=12mm] (feedback) {};
       \node[coordinate, right of=gain, node distance=20mm] (output) {};

       \draw[->] (input) -- node[above, pos=0.3] {$r(t)$} (sum);
       \draw[->] (sum) -- node[above, pos=0.2] {$e(t)$} node[coordinate] (mm) {}  (ii);
       \draw[->] (gain) -- node[above, near end] {$u(t)$} (output);
       \draw[->] (feedback) -- node[left, near start] {$y(t)$} node[right, pos=0.95] {-} (sum);
       \draw[->, color=ppc] (mm) |- (pp) -| node[right,] {$u_P(t)$} (sum2);
       \draw[->, color=ddc] (feedback |- dd) -- node[above, pos=0.95] {-} (dd) -| node[right,] {$u_D(t)$}   (sum2);
       \draw[->, color=iic] (ii)  -- node[above,] {$u_I(t)$} (sum2);
       \draw[->] (sum2) -- node[above, near end] {} (gain);

     \end{tikzpicture}
     \small
     \(  u(t) = k_c\Big( \textcolor{ppc}{e(t)} + \textcolor{iic}{\overbrace{\frac{1}{\tau_i} \int_0^{t} e(\xi) d\xi}^{u_I(t)}} + \textcolor{ddc}{ \underbrace{\tau_d \frac{d}{dt} \big(-y(t)\big)}_{u_D(t)}} \Big)\)
   \end{center}
   #+end_export

   #+begin_export latex
      \begin{center}
      \def\wn{2}
      \def\zz{0.3}
      \pgfmathsetmacro{\wwd}{\wn*sqrt(1-\zz*\zz)}
      \pgfmathsetmacro{\zwn}{\zz*\wn}
     \pgfmathsetmacro{\thangle}{acos(\zz)}
      \begin{tikzpicture}
      \begin{axis}[
       clip=false,
       width=14cm,
       height=4.5cm,
       ylabel={},
       xlabel={$t$},
       ymax = 2,
       ymin = -0.5,
       ]
	 \addplot[black, no marks, domain=-0.4:8, samples=200] {(x>0)*(1 - exp(-x * \zwn)/sqrt(1-\zz*\zz) * sin(deg(\wwd*x) + \thangle))} node[coordinate, pin=20:{$y(t)$}, pos=0.3] {};
	 \addplot[color=ppc, no marks, domain=-0.4:8, samples=600] {(x>0)*(exp(-x * \zwn)/sqrt(1-\zz*\zz) * sin(deg(\wwd*x) + \thangle))} node[coordinate, pin=200:{$e(t)$}, pos=0.3] {};
	 \addplot [color=iic, thick] table [y=int] {\pidtable};
	 \addplot[magenta!70!black, no marks, domain=-0.4:8, samples=200] coordinates {(-0.4, 0) (0,0) (0,1) (8,1)} node[coordinate, pin=90:{$r(t)$}, pos=0.2] {};
       \end{axis}

    \end{tikzpicture}
   \end{center}
   #+end_export
 
* Windup

** Integral windup
   
   
   [[https://tecdemonterrey.instructuremedia.com/embed/6fb197b1-38a6-4938-b622-b25d4a45efcc][Video by Tomás Alejandro Lugo Salinas (MTY)]] 

* Anti-windup

** Anti-windup using back-calculation 
   #+begin_center
   \includegraphics[width=1.02\linewidth]{../../figures/anti-windup-back-calculation.png}
   #+end_center
