#+OPTIONS: toc:nil
# #+LaTeX_CLASS: koma-article 

#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation,aspectratio=169, usenames, dvipsnames]
#+OPTIONS: H:2

#+LaTex_HEADER: \usepackage{khpreamble}
#+LaTex_HEADER: \usepackage{amssymb}
#+LaTex_HEADER: \usepgfplotslibrary{groupplots}

#+LaTex_HEADER: \newcommand*{\shift}{\operatorname{q}}
#+LaTex_HEADER:   \definecolor{ppc}{rgb}{0.1,0.1,0.6}
#+LaTex_HEADER:   \definecolor{iic}{rgb}{0.6,0.1,0.1}
#+LaTex_HEADER:   \definecolor{ddc}{rgb}{0.1,0.6,0.1}
#+LaTex_HEADER: \usetikzlibrary{positioning,circuits.plc.ladder}

#+LaTex_HEADER: \newcommand*{\coil}[1]{to[short] ++(0.5, 0) node[coordinate] (orig) {} arc [start angle=180, end angle=150,radius=8mm] (orig) arc [start angle=180, end angle=210,radius=8mm] (orig) ++(1cm, 0) node[coordinate] (coilend) {} arc [start angle=0, end angle=30,radius=8mm] (coilend) arc [start angle=0, end angle=-30,radius=8mm] (coilend) to[short] ++(0.5cm, 0) (orig) ++(0.5, 0.8) node {#1}}


#+title: Sistemas de control y automatización
# #+date: 2020-09-01

* What do I want the students to understand?			   :noexport:
  - Why feedback is important
  - Basic P&I Diagrams
  - Modeling
    - First principle
    - From experiment
  - Laplace trf
  - Closed-loop systems, Mason's gain rule
  - Characteristic eqn
  - Root locus
  - PID
  - Digital logic
    - Combinatorial
    - Sequential
  - Symbols of pneumatics


* Which activities will the students do?			   :noexport:
  - Block diagram feedback system
  - Root locus simple case
  - PID intuition

* Ceneval

** CENEVAL

\begin{center}
  \includegraphics[width=.7\linewidth]{./subareas.png}
\end{center}

** CENEVAL

\begin{center}
  \includegraphics[width=.7\linewidth]{./seccion-D.png}
\end{center}


* Feedback 

** Sistemas de control son ubicuos

\begin{center}
  \includegraphics[width=.6\linewidth]{../figures/PnID-ex.png}
\end{center}

*** Notes                                                          :noexport:

- Part in a food-processing plant.
- Type of diagram: Piping and Instrumentation Diagram
- Tank providing a flow of warm, sweat fluid.
- Valves, heating jacket.
- Q: How many feedback loops?


** Control en lazo cerrado

#+begin_export latex
\begin{center}
\begin{tikzpicture}[node distance=20mm,
                    block/.style={rectangle, draw, minimum width=15mm, inner sep=3mm},
                    sumnode/.style={circle, draw, inner sep=3pt}]
  \node[coordinate] (input) {};
  \node[sumnode, right of=input] (sum) {};
   \node[block, right of=sum,] (lti) {Controller};
   \node[block, right of=lti, node distance=30mm] (lti2) {Plant};
   \node[coordinate, right of=lti2, node distance=30mm] (output) {};
   \draw[->] (input) -- node[near start, above] {$r(t)$}  (sum);
   \draw[->] (sum) -- node[ above] {}  (lti);
   \draw[->] (lti) -- node[ above] {$u(t)$}  (lti2);
   \draw[->] (lti2) -- node[coordinate] (meas) {} node[near end, above] {$y(t)$} (output);
   \draw[->] (meas) -- ++(0, -14mm) -| node[left, pos=0.96] {$-$} (sum);
 \end{tikzpicture}
\end{center}

#+end_export

*** Notes                                                          :noexport:

- Examples:
  | Input                     | Output                               |
  |---------------------------+--------------------------------------|
  | Torque in motor           | Angle of arm in robot manipulator    |
  | Voltage in motor armature | Angular velocity of motor            |
  | Thrust from rockets       | Position and orientation of satelite |
  | Opening of a valve        | Level in a tank                      |
  | Flow of steam             | Temperature in a tank reactor        |
  | Position of fuel rods     | Heat generated in a nuclear reactor  |


** Control en lazo cerrado


#+begin_export latex
\begin{center}
\begin{tikzpicture}[scale = 0.7, node distance=20mm,
                    block/.style={rectangle, draw, minimum width=15mm, inner sep=3mm},
                    sumnode/.style={circle, draw, inner sep=3pt}]
  \node[coordinate] (input) {};
  \node[sumnode, right of=input] (sum) {};
   \node[block, right of=sum,] (lti) {Controller};
   \node[block, right of=lti, node distance=30mm] (lti2) {Plant};
   \node[coordinate, right of=lti2, node distance=30mm] (output) {};
   \draw[->] (input) -- node[near start, above] {$r(t)$}  (sum);
   \draw[->] (sum) -- node[ above] {}  (lti);
   \draw[->] (lti) -- node[ above] {$u(t)$}  (lti2);
   \draw[->] (lti2) -- node[coordinate] (meas) {} node[near end, above] {$y(t)$} (output);
   \draw[->] (meas) -- ++(0, -14mm) -| node[left, pos=0.96] {$-$} (sum);
 \end{tikzpicture}
\end{center}

#+end_export

*Diseño de control:* Determinar un controlador para que el sistema en lazo cerrado cumple con ciertas *especificaciones de rendimiento*. 

*** Notes                                                          :noexport:

What is *good performance*?

** Especificaciones de rendimiento
\begin{center}
  \includegraphics[width=.8\linewidth]{../figures/step-response-specifications}
\end{center}

*** Notes                                                            :noexport:

PO = (ymax - yf)/yf * 100


** Especificaciones de rendimiento

 *Actividad* ¿Cumple el sistema con las especificaciones?

*** Text
:PROPERTIES:
:BEAMER_col: 0.4
:END:

 | Sobreimpulso            | < 20%  |
 | Tiempo de levantamiento | < 1.5s |

 
*** Graphics
:PROPERTIES:
:BEAMER_col: 0.6
:END:

    \begin{center}
     \includegraphics[width=1.0\linewidth]{../figures/second-order-response-example}
    \end{center}

*** Notes                                                            :noexport:

Each vert div 0.05,
Each hor div 0.5,
Overshoot, PO = (1.17-1)/1 * 100 = 17%

t_10 = 0.5
t_90 = 2.2

t_r = t_90 - t_10 = 2.2 - 0.5 = 1.7 s



* Modeling
** Sistemas de primer orden

\begin{center}
\begin{tikzpicture}[node distance=20mm,
                    block/.style={rectangle, draw, minimum width=15mm, inner sep=3mm},
                    sumnode/.style={circle, draw, inner sep=3pt}]
  \node[coordinate] (input) {};
   \node[block, right of=input,] (lti) {$\frac{K}{s\tau + 1}$};
   \node[coordinate, right of=lti, node distance=20mm] (output) {};
   \draw[->] (input) -- node[near start, above] {$u(t)$}  (lti);
   \draw[->] (lti) -- node[coordinate] (meas) {} node[near end, above] {$y(t)$} (output);
 \end{tikzpicture}
\end{center}



** Respuesta al escalón por medio de la transformada de Laplace

*** Parametrizaciónes alternativas

\[ \frac{d}{dt} y + \alpha y = \beta u  \qquad \Leftrightarrow \qquad \tau \frac{d}{dt} y + y = k u \]

*** Notes                                                          :noexport:

tau s Y + Y = k U
Y = k/(s tau + 1) U, U=uf/s

Y = k uf / ( s(stau+1)) = k uf (A/s + B/(s tau + 1)) = k uf  ( A(stau + 1) + Bs ) / s(s tau + 1)
= k uf ( (A tau  + B) s + A ) / s(s tau + 1)

A = 1
B = -tau

Y = k uf ( 1/s - tau/(s tau + 1) )  => y(t) = k uf (1 - exp(-t/tau) )



** Función de transferencia por prueba

   \[  \quad \textcolor{green!50!black}{Y(s)} = \frac{K}{s\tau + 1}\textcolor{blue!80!black}{U(s)} \quad \overset{U(s) = \frac{u_f}{s}}{\Longrightarrow} \quad \textcolor{green!50!black}{y(t)} = u_f K\big( 1 - \mathrm{e}^{-\frac{t}{\tau}}\big)u_H(t)\]
   #+begin_export latex
   \def\Tcnst{3}
   \def\tdelay{0.0}
   \def\ggain{2}
   \def\uampl{0.8}
   \pgfmathsetmacro{\yfinal}{\uampl*\ggain}
   \pgfmathsetmacro{\yone}{0.283*\yfinal}
   \pgfmathsetmacro{\ytwo}{0.632*\yfinal}
   \pgfmathsetmacro{\tone}{\tdelay + \Tcnst/3}
   \pgfmathsetmacro{\two}{\tdelay + \Tcnst}

   \begin{center}
     \begin{tikzpicture}
       \begin{axis}[
       width=14cm,
       height=4.5cm,
       grid = both,
       xtick = {0,  \two},
       xticklabels = {0, $\tau$},
       ytick = {0, \ytwo, \uampl, \yfinal},
       yticklabels = {0,  $ $, $u_f$, $y_f$},
       xmin = -0.2,
       %minor y tick num=9,
       %minor x tick num=9,
       %every major grid/.style={red, opacity=0.5},
       xlabel = {$t$},
       ]
	 \addplot [thick, green!50!black, no marks, domain=0:10, samples=100] {\uampl*\ggain*(x>\tdelay)*(1 - exp(-(x-\tdelay)/\Tcnst)} node [coordinate, pos=0.9, pin=-90:{$y(t)$}] {};
	 \addplot [const plot, thick, blue!80!black, no marks, domain=-1:10, samples=100] coordinates {(-1,0) (0,0) (0,\uampl) (10,\uampl)} node [coordinate, pos=0.9, pin=-90:{$u(t)$}] {};
       \end{axis}
     \end{tikzpicture}
   \end{center}
   #+end_export

   *Actividad* Evalua la respuesta $y(t)$ por $t=\tau$,  y por \(t\to\infty\)!

** Función de transferencia por prueba

   \[  \quad \textcolor{green!50!black}{Y(s)} = \frac{K}{s\tau + 1}\textcolor{blue!80!black}{U(s)} \quad \overset{U(s) = \frac{u_f}{s}}{\Longrightarrow} \quad \textcolor{green!50!black}{y(t)} = u_f K\big( 1 - \mathrm{e}^{-\frac{t}{\tau}}\big)u_H(t)\]
   #+begin_export latex
   \def\Tcnst{3}
   \def\tdelay{0.0}
   \def\ggain{2}
   \def\uampl{0.8}
   \pgfmathsetmacro{\yfinal}{\uampl*\ggain}
   \pgfmathsetmacro{\yone}{0.283*\yfinal}
   \pgfmathsetmacro{\ytwo}{0.632*\yfinal}
   \pgfmathsetmacro{\tone}{\tdelay + \Tcnst/3}
   \pgfmathsetmacro{\two}{\tdelay + \Tcnst}

   \begin{center}
     \small
     \begin{tikzpicture}
       \begin{axis}[
       width=14cm,
       height=3.5cm,
       grid = both,
       xtick = {0,  \two},
       xticklabels = {0, $\tau$},
       ytick = {0, \ytwo, \uampl, \yfinal},
       yticklabels = {0,  $0.632y_f$, $u_f$, $y_f$},
       xmin = -0.2,
       %minor y tick num=9,
       %minor x tick num=9,
       %every major grid/.style={red, opacity=0.5},
       xlabel = {$t$},
       ]
	 \addplot [thick, green!50!black, no marks, domain=0:10, samples=100] {\uampl*\ggain*(x>\tdelay)*(1 - exp(-(x-\tdelay)/\Tcnst)} node [coordinate, pos=0.9, pin=-90:{$y(t)$}] {};
	 \addplot [const plot, thick, blue!80!black, no marks, domain=-1:10, samples=100] coordinates {(-1,0) (0,0) (0,\uampl) (10,\uampl)} node [coordinate, pos=0.9, pin=-90:{$u(t)$}] {};
       \end{axis}
     \end{tikzpicture}
   \end{center}
   #+end_export

   *Constante de tiempo:* El tiempo $t=\tau$ que tarde la respuesta en llegar a 63.2% del valor final.

   *Ganancia:* \(y_f = \lim_{t\to\infty}y(t) = Ku_f \quad \Rightarrow \quad K = \frac{y_f}{u_f}\)

** Animación

[[https://kjartan-at-tec.github.io/mr2023/time-response-3.svg][Sistemas de primer orden]]


** Sistemas de primer orden con retraso

\begin{center}
\begin{tikzpicture}[node distance=20mm,
                    block/.style={rectangle, draw, minimum width=15mm, inner sep=3mm},
                    sumnode/.style={circle, draw, inner sep=3pt}]
  \node[coordinate] (input) {};
   \node[block, right of=input,] (lti) {$\frac{k\mathrm{e}^{-s\theta}}{s\tau + 1}$};
   \node[coordinate, right of=lti, node distance=20mm] (output) {};
   \draw[->] (input) -- node[near start, above] {$u(t)$}  (lti);
   \draw[->] (lti) -- node[coordinate] (meas) {} node[anchor=west,near end, above] {$y(t)$} (output);
 \end{tikzpicture}
\end{center}

** Intermezzo: La función de transferencia de un retraso

\begin{center}
\begin{tikzpicture}[node distance=20mm,
                    block/.style={rectangle, draw, minimum width=15mm, inner sep=3mm},
                    sumnode/.style={circle, draw, inner sep=3pt}]
  \node[coordinate] (input) {};
   \node[block, right of=input,] (lti) {$\mathrm{e}^{-s\theta}$};
   \node[coordinate, right of=lti, node distance=20mm] (output) {};
   \draw[->] (input) -- node[near start, above] {$u(t)$}  (lti);
   \draw[->] (lti) -- node[coordinate] (meas) {} node[near end, above, anchor=south west] {$y(t)=u(t-\theta)$} (output);
 \end{tikzpicture}
\end{center}

\[ Y(s) = \laplace{y(t)} = \int_0^\infty y(t) \mathrm{e}^{-st} dt \]

*** Notes                                                          :noexport:

\int u(t-\theta) exp(-st) dt
change of variables tau=t-theta, t = tau + theta, dt = dtau
limits: lower t=0 <=> tau=-theta, but functions zero for negative times

\int u(tau) exp(-s(tau+theta)) = exp(-s theta) \int u(tau) exp(-stau) dtau = exp(-s theta) U(s)

** Función de transferencia por prueba
   Modelo de primer orden con constante de tiempo \(\tau\) y retraso \(\theta\)
   \[  \quad \textcolor{green!50!black}{Y(s)} = \frac{K\mathrm{e}^{-s\theta}}{s\tau + 1}\textcolor{blue!80!black}{U(s)} \quad \overset{U(s) = \frac{u_f}{s}}{\Longrightarrow} \quad \textcolor{green!50!black}{y(t)} = u_f K\big( 1 - \mathrm{e}^{-\frac{t-\theta}{\tau}}\big)u_H(t-\theta)\]
   #+begin_export latex
   \def\Tcnst{3}
   \def\tdelay{0.6}
   \def\ggain{2}
   \def\uampl{0.8}
   \pgfmathsetmacro{\yfinal}{\uampl*\ggain}
   \pgfmathsetmacro{\yone}{0.283*\yfinal}
   \pgfmathsetmacro{\ytwo}{0.632*\yfinal}
   \pgfmathsetmacro{\tone}{\tdelay + \Tcnst/3}
   \pgfmathsetmacro{\two}{\tdelay + \Tcnst}

   \begin{center}
     \begin{tikzpicture}
       \begin{axis}[
       width=14cm,
       height=4.5cm,
       grid = both,
       xtick = {0, \tdelay, \tone, \two},
       xticklabels = {0, $\theta$, $\theta+\frac{\tau}{3}$, $\theta + \tau$},
       ytick = {0, \yone, \ytwo, \uampl, \yfinal},
       yticklabels = {0, $ $, $ $, $u_f$, $y_f$},
       xmin = -0.2,
       %minor y tick num=9,
       %minor x tick num=9,
       %every major grid/.style={red, opacity=0.5},
       xlabel = {$t$},
       ]
	 \addplot [thick, green!50!black, no marks, domain=0:10, samples=100] {\uampl*\ggain*(x>\tdelay)*(1 - exp(-(x-\tdelay)/\Tcnst)} node [coordinate, pos=0.9, pin=-90:{$y(t)$}] {};
	 \addplot [const plot, thick, blue!80!black, no marks, domain=-1:10, samples=100] coordinates {(-1,0) (0,0) (0,\uampl) (10,\uampl)} node [coordinate, pos=0.9, pin=-90:{$u(t)$}] {};
       \end{axis}
     \end{tikzpicture}
   \end{center}
   #+end_export

   *Actividad* Evalua la respuesta  $y(t)$ por $t=\theta + \frac{\tau}{3}$ y $t=\theta + \tau$!


** Función de transferencia por prueba
   Modelo de primer orden con constante de tiempo \(\tau\) y retraso \(\theta\)
   \[  \quad \textcolor{green!50!black}{Y(s)} = \frac{K\mathrm{e}^{-s\theta}}{s\tau + 1}\textcolor{blue!80!black}{U(s)} \quad \overset{U(s) = \frac{u_f}{s}}{\Longrightarrow} \quad \textcolor{green!50!black}{y(t)} = u_f K\big( 1 - \mathrm{e}^{-\frac{t-\theta}{\tau}}\big)u_H(t-\theta)\]
   #+begin_export latex
   \def\Tcnst{3}
   \def\tdelay{0.6}
   \def\ggain{2}
   \def\uampl{0.8}
   \pgfmathsetmacro{\yfinal}{\uampl*\ggain}
   \pgfmathsetmacro{\yone}{0.283*\yfinal}
   \pgfmathsetmacro{\ytwo}{0.632*\yfinal}
   \pgfmathsetmacro{\tone}{\tdelay + \Tcnst/3}
   \pgfmathsetmacro{\two}{\tdelay + \Tcnst}

   \begin{center}
     \begin{tikzpicture}
       \begin{axis}[
       width=14cm,
       height=4.5cm,
       grid = both,
       xtick = {0, \tdelay, \tone, \two},
       xticklabels = {0, $\theta$, $\theta+\frac{\tau}{3}$, $\theta + \tau$},
       ytick = {0, \yone, \ytwo, \uampl, \yfinal},
       yticklabels = {0, $0.283y_{f}$, $0.632y_f$, $u_f$, $y_f$},
       xmin = -0.2,
       %minor y tick num=9,
       %minor x tick num=9,
       %every major grid/.style={red, opacity=0.5},
       xlabel = {$t$},
       ]
	 \addplot [thick, green!50!black, no marks, domain=0:10, samples=100] {\uampl*\ggain*(x>\tdelay)*(1 - exp(-(x-\tdelay)/\Tcnst)} node [coordinate, pos=0.9, pin=-90:{$y(t)$}] {};
	 \addplot [const plot, thick, blue!80!black, no marks, domain=-1:10, samples=100] coordinates {(-1,0) (0,0) (0,\uampl) (10,\uampl)} node [coordinate, pos=0.9, pin=-90:{$u(t)$}] {};
       \end{axis}
     \end{tikzpicture}
   \end{center}
   #+end_export

   \[ y_f = \lim_{t\to\infty} y(t) = u_f K \quad \Rightarrow \quad K = \frac{y_f}{u_f}. \]

** Función de transferencia por prueba - ejemplo
   \[  \quad Y(s) = \frac{K\mathrm{e}^{-s\theta}}{s\tau + 1}U(s) \quad \overset{U(s) = \frac{u_f}{s}}{\Longrightarrow} \quad y(t) = u_f K\big( 1 - \mathrm{e}^{-\frac{t-\theta}{\tau}}\big)u_s(t-\theta)\]
   #+begin_export latex
   \def\Tcnst{2.1}
   \def\tdelay{1}
   \def\ggain{2}
   \def\uampl{0.8}
   \pgfmathsetmacro{\yfinal}{\uampl*\ggain}
   \pgfmathsetmacro{\yone}{0.283*\yfinal}
   \pgfmathsetmacro{\ytwo}{0.632*\yfinal}
   \pgfmathsetmacro{\tone}{\tdelay + \Tcnst/3}
   \pgfmathsetmacro{\two}{\tdelay + \Tcnst}

   \begin{center}
     \begin{tikzpicture}
       \begin{axis}[
       width=12cm,
       height=4cm,
       grid = both,
       %xtick = {0, \tdelay, \tone, \two},
       %xticklabels = {0, $\theta$, $\theta+\frac{\tau}{3}$, $\theta + \tau$},
       %ytick = {0, \yone, \ytwo, \uampl, \yfinal},
       %yticklabels = {0, $0.283y_{f}$, $0.632y_f$, $u_f$, $y_f$},
       xmin = -0.2,
       minor y tick num=9,
       minor x tick num=9,
       every major grid/.style={red, opacity=0.5},
       %xlabel = {$t$},
       clip = false,
       ]
	 \addplot [thick, green!50!black, smooth, no marks, domain=0:10, samples=16] {\uampl*\ggain*(x>\tdelay)*(1 - exp(-(x-\tdelay)/\Tcnst)} node [coordinate, pos=0.9, pin=-90:{$y(t)$}] {};
	 \addplot [const plot, thick, blue!80!black, no marks, domain=-1:10, samples=100] coordinates {(-1,0) (0,0) (0,\uampl) (10,\uampl)} node [coordinate, pos=0.9, pin=-90:{$u(t)$}] {};
	 \draw[thick, green!70!black, dashed] (axis cs: 10, \yfinal) -- (axis cs: -1, \yfinal, -0.9) node[left, anchor=east] {$y_f = \yfinal$}; 
	 \draw[blue!70!black, dashed] (axis cs: 0, \uampl) -- (axis cs: -1, \uampl, -0.9) node[left, anchor=east] {$u_f = \uampl$}; 
       \end{axis}
     \end{tikzpicture}
   \end{center}
   #+end_export

** Función de transferencia por prueba - ejemplo
   \[  \quad Y(s) = \frac{K\mathrm{e}^{-s\theta}}{s\tau + 1}U(s) \quad \overset{U(s) = \frac{u_f}{s}}{\Longrightarrow} \quad y(t) = u_f K\big( 1 - \mathrm{e}^{-\frac{t-\theta}{\tau}}\big)u_s(t-\theta)\]
   #+begin_export latex
   \def\Tcnst{2.1}
   \def\tdelay{1}
   \def\ggain{2}
   \def\uampl{0.8}
   \pgfmathsetmacro{\yfinal}{\uampl*\ggain}
   \pgfmathsetmacro{\yone}{0.283*\yfinal}
   \pgfmathsetmacro{\ytwo}{0.632*\yfinal}
   \pgfmathsetmacro{\tone}{\tdelay + \Tcnst/3}
   \pgfmathsetmacro{\two}{\tdelay + \Tcnst}

   \begin{center}
     \begin{tikzpicture}
       \begin{axis}[
       width=12cm,
       height=4cm,
       grid = both,
       %xtick = {0, \tdelay, \tone, \two},
       %xticklabels = {0, $\theta$, $\theta+\frac{T}{3}$, $\theta + T$},
       %ytick = {0, \yone, \ytwo, \uampl, \yfinal},
       %yticklabels = {0, $0.283y_{f}$, $0.632y_f$, $u_f$, $y_f$},
       xmin = -0.2,
       minor y tick num=9,
       minor x tick num=9,
       every major grid/.style={red, opacity=0.5},
       %xlabel = {$t$},
       clip = false,
       ]
	 \addplot [thick, green!50!black, smooth, no marks, domain=0:10, samples=16] {\uampl*\ggain*(x>\tdelay)*(1 - exp(-(x-\tdelay)/\Tcnst)} node [coordinate, pos=0.9, pin=-90:{$y(t)$}] {};
	 \addplot [const plot, thick, blue!80!black, no marks, domain=-1:10, samples=100] coordinates {(-1,0) (0,0) (0,\uampl) (10,\uampl)} node [coordinate, pos=0.9, pin=-90:{$u(t)$}] {};
	 \draw[thick, orange, dashed] (axis cs: \two, \ytwo) -- (axis cs: \two, -0.9) node[below] {$t_2 = \two = \theta + \tau$}; 
	 \draw[thick, orange, dashed] (axis cs: \two, \ytwo) -- (axis cs: -1, \ytwo, -0.9) node[left, anchor=east] {$0.632y_f = \ytwo$}; 
	 \draw[thick, green!70!black, dashed] (axis cs: 10, \yfinal) -- (axis cs: -1, \yfinal, -0.9) node[left, anchor=east] {$y_f = \yfinal$}; 
	 \draw[blue!70!black, dashed] (axis cs: 0, \uampl) -- (axis cs: -1, \uampl, -0.9) node[left, anchor=east] {$u_f = \uampl$}; 
       \end{axis}
     \end{tikzpicture}
   \end{center}
   #+end_export
   
** Función de transferencia por prueba - ejemplo
   \[  \quad Y(s) = \frac{K\mathrm{e}^{-s\theta}}{s\tau + 1}U(s) \quad \overset{U(s) = \frac{u_f}{s}}{\Longrightarrow} \quad y(t) = u_f K\big( 1 - \mathrm{e}^{-\frac{t-\theta}{\tau}}\big)u_s(t-\theta)\]
   #+begin_export latex
   \def\Tcnst{2.1}
   \def\tdelay{1}
   \def\ggain{2}
   \def\uampl{0.8}
   \pgfmathsetmacro{\yfinal}{\uampl*\ggain}
   \pgfmathsetmacro{\yone}{0.283*\yfinal}
   \pgfmathsetmacro{\ytwo}{0.632*\yfinal}
   \pgfmathsetmacro{\tone}{\tdelay + \Tcnst/3}
   \pgfmathsetmacro{\two}{\tdelay + \Tcnst}

   \begin{center}
     \begin{tikzpicture}
       \begin{axis}[
       width=12cm,
       height=4cm,
       grid = both,
       %xtick = {0, \tdelay, \tone, \two},
       %xticklabels = {0, $\theta$, $\theta+\frac{T}{3}$, $\theta + T$},
       %ytick = {0, \yone, \ytwo, \uampl, \yfinal},
       %yticklabels = {0, $0.283y_{f}$, $0.632y_f$, $u_f$, $y_f$},
       xmin = -0.2,
       minor y tick num=9,
       minor x tick num=9,
       every major grid/.style={red, opacity=0.5},
       %xlabel = {$t$},
       clip = false,
       ]
	 \addplot [thick, green!50!black, smooth, no marks, domain=0:10, samples=16] {\uampl*\ggain*(x>\tdelay)*(1 - exp(-(x-\tdelay)/\Tcnst)} node [coordinate, pos=0.9, pin=-90:{$y(t)$}] {};
	 \addplot [const plot, thick, blue!80!black, no marks, domain=-1:10, samples=100] coordinates {(-1,0) (0,0) (0,\uampl) (10,\uampl)} node [coordinate, pos=0.9, pin=-90:{$u(t)$}] {};
	 \draw[thick, red, dashed] (axis cs: \tone, \yone) -- (axis cs: \tone, -0.45) node[below] {$t_1 = \tone = \theta + \frac{\tau}{3}$}; 
	 \draw[thick, red, dashed] (axis cs: \tone, \yone) -- (axis cs: -1,\yone) node[left, anchor=east] {$0.283y_f = \yone$}; 
	 \draw[thick, orange, dashed] (axis cs: \two, \ytwo) -- (axis cs: \two, -0.9) node[below] {$t_2 = \two = \theta + \tau$}; 
	 \draw[thick, orange, dashed] (axis cs: \two, \ytwo) -- (axis cs: -1, \ytwo, -0.9) node[left, anchor=east] {$0.632y_f = \ytwo$}; 
	 \draw[thick, green!70!black, dashed] (axis cs: 10, \yfinal) -- (axis cs: -1, \yfinal, -0.9) node[left, anchor=east] {$y_f = \yfinal$}; 
	 \draw[blue!70!black, dashed] (axis cs: 0, \uampl) -- (axis cs: -1, \uampl, -0.9) node[left, anchor=east] {$u_f = \uampl$}; 
       \end{axis}
     \end{tikzpicture}
   \end{center}
   #+end_export

** Función de transferencia por prueba - ejemplo
   \[  \quad Y(s) = \frac{K\mathrm{e}^{-s\theta}}{s\tau + 1}U(s) \quad \overset{U(s) = \frac{u_f}{s}}{\Longrightarrow} \quad y(t) = u_f K\big( 1 - \mathrm{e}^{-\frac{t-\theta}{\tau}}\big)u_s(t-\theta)\]
   #+begin_export latex
   \def\Tcnst{2.1}
   \def\tdelay{1}
   \def\ggain{2}
   \def\uampl{0.8}
   \pgfmathsetmacro{\yfinal}{\uampl*\ggain}
   \pgfmathsetmacro{\yone}{0.283*\yfinal}
   \pgfmathsetmacro{\ytwo}{0.632*\yfinal}
   \pgfmathsetmacro{\tone}{\tdelay + \Tcnst/3}
   \pgfmathsetmacro{\two}{\tdelay + \Tcnst}

   \begin{center}
     \begin{tikzpicture}
       \begin{axis}[
       width=12cm,
       height=4cm,
       grid = both,
       %xtick = {0, \tdelay, \tone, \two},
       %xticklabels = {0, $\theta$, $\theta+\frac{T}{3}$, $\theta + T$},
       %ytick = {0, \yone, \ytwo, \uampl, \yfinal},
       %yticklabels = {0, $0.283y_{f}$, $0.632y_f$, $u_f$, $y_f$},
       xmin = -0.2,
       minor y tick num=9,
       minor x tick num=9,
       every major grid/.style={red, opacity=0.5},
       %xlabel = {$t$},
       clip = false,
       ]
	 \addplot [thick, green!50!black, smooth, no marks, domain=0:10, samples=16] {\uampl*\ggain*(x>\tdelay)*(1 - exp(-(x-\tdelay)/\Tcnst)} node [coordinate, pos=0.9, pin=-90:{$y(t)$}] {};
	 \addplot [const plot, thick, blue!80!black, no marks, domain=-1:10, samples=100] coordinates {(-1,0) (0,0) (0,\uampl) (10,\uampl)} node [coordinate, pos=0.9, pin=-90:{$u(t)$}] {};
	 \draw[thick, red, dashed] (axis cs: \tone, \yone) -- (axis cs: \tone, -0.45) node[below] {$t_1 = \tone = \theta + \frac{\tau}{3}$}; 
	 \draw[thick, red, dashed] (axis cs: \tone, \yone) -- (axis cs: -1,\yone) node[left, anchor=east] {$0.283y_f = \yone$}; 
	 \draw[thick, orange, dashed] (axis cs: \two, \ytwo) -- (axis cs: \two, -0.9) node[below] {$t_2 = \two = \theta + \tau$}; 
	 \draw[thick, orange, dashed] (axis cs: \two, \ytwo) -- (axis cs: -1, \ytwo, -0.9) node[left, anchor=east] {$0.632y_f = \ytwo$}; 
	 \draw[thick, green!70!black, dashed] (axis cs: 10, \yfinal) -- (axis cs: -1, \yfinal, -0.9) node[left, anchor=east] {$y_f = \yfinal$}; 
	 \draw[blue!70!black, dashed] (axis cs: 0, \uampl) -- (axis cs: -1, \uampl, -0.9) node[left, anchor=east] {$u_f = \uampl$}; 
       \end{axis}
     \end{tikzpicture}
   \end{center}
   #+end_export
   \[ \begin{cases} \tone = \theta + \frac{\tau}{3}\\ \two = \theta + \tau \end{cases} \quad \Rightarrow \quad \begin{cases} \theta = \tdelay \\ \tau = \Tcnst \end{cases}, \qquad  K = \frac{y_f}{u_f} = \frac{\yfinal}{\uampl} = \ggain \]


** Sistemas de segundo orden


[[https://kjartan-at-tec.github.io/mr2023/time-response-4.svg][Sistemas de segundo orden]]


* Laplace and block diagrams                                       :noexport:
** Block diagram algebra

\begin{center}
  \includegraphics[width=.6\linewidth]{../figures/block-simple-feedback}
\end{center}

Transfer function from $r(t)$ to $y(t)$:
\[ \frac{Y(s)}{R(s)} = \frac{G(s)}{ 1+ G(s)}\]


** Block diagram algebra

 *Activity* Pair the block-diagram with the correct closed-loop transfer function!


#+ATTR_LATEX:  :center :environment longtable :align cccc
| \textcolor{red}{A}                                                       | \textcolor{red}{B}                                                        | \textcolor{red}{C}                                                        |  \textcolor{red}{D}                                                       |
| \includegraphics[width=3cm]{../figures/block-simple-control-feedback}    | \includegraphics[width=3cm]{../figures/block-simple-control-feedback2}    | \includegraphics[width=3cm]{../figures/block-simple-control-feedback3}    | \includegraphics[width=3cm]{../figures/block-simple-control-feedback4}    |


#+ATTR_LATEX:  :center :environment longtable :align cccc
| \textcolor{blue!80!black}{I}                     | \textcolor{blue!80!black}{II}                              | \textcolor{blue!80!black}{III}                      |                                                   \textcolor{blue!80!black}{IV}    |
| \( \frac{Y(s)}{R(s)}=\frac{G(s)F(s)}{1 + G(s)}\) | \(\quad \frac{Y(s)}{R(s)}=\frac{G(s)}{1 + G(s)F(s)}\quad\) | \(\frac{Y(s)}{R(s)}=\frac{1}{1 + G(s)F(s)}\)        | \(\frac{Y(s)}{R(s)}=\frac{G(s)F(s)}{1 + G(s)F(s)}\) |


*** Notes                                                          :noexport:
Solution

A - IV
B - II
C - I
D - III


* PID control

** PID control
** Control en lazo cerrado

#+begin_export latex
\begin{center}
\begin{tikzpicture}[node distance=20mm,
                    block/.style={rectangle, draw, minimum width=15mm, inner sep=3mm},
                    sumnode/.style={circle, draw, inner sep=3pt}]
  \node[coordinate] (input) {};
  \node[sumnode, right of=input] (sum) {};
   \node[block, right of=sum,] (lti) {$F(s)$};
   \node[block, right of=lti, node distance=30mm] (lti2) {$G(s)$};
   \node[coordinate, right of=lti2, node distance=30mm] (output) {};
   \draw[->] (input) -- node[near start, above] {$r(t)$}  (sum);
   \draw[->] (sum) -- node[ above] {$e(t)$}  (lti);
   \draw[->] (lti) -- node[ above] {$u(t)$}  (lti2);
   \draw[->] (lti2) -- node[coordinate] (meas) {} node[near end, above] {$y(t)$} (output);
   \draw[->] (meas) -- ++(0, -14mm) -| node[left, pos=0.96] {$-$} (sum);
 \end{tikzpicture}
\end{center}

#+end_export

** Controlador PID - Formas estándar
   \definecolor{ppc}{rgb}{0.1,0.1,0.6}
   \definecolor{iic}{rgb}{0.6,0.1,0.1}
   \definecolor{ddc}{rgb}{0.1,0.6,0.1}
   
   #+begin_export latex
   \begin{center}
     \begin{tikzpicture}[node distance=22mm, block/.style={rectangle, draw, minimum width=15mm}, sumnode/.style={circle, draw, inner sep=2pt}]
    
       \node[coordinate] (input) {};
       \node[sumnode, right of=input, node distance=16mm] (sum) {\tiny $\Sigma$};
       \node[color=iic,block, right of=sum, node distance=28mm] (ii)  {$\frac{1}{\tau_is}$};
       \node[color=ppc, coordinate, above of=ii, node distance=10mm] (pp)  {};
       \node[color=ddc,block, below of=ii, node distance=10mm] (dd)  {$\tau_ds$};
       \node[sumnode, right of=ii, node distance=20mm] (sum2) {\tiny $\Sigma$};
       \node[block, right of=sum2, node distance=20mm] (gain)  {$k_c$};
       \node[coordinate, below of=sum, node distance=12mm] (feedback) {};
       \node[coordinate, right of=gain, node distance=20mm] (output) {};

       \draw[->] (input) -- node[above, pos=0.3] {$r(t)$} (sum);
       \draw[->] (sum) -- node[above, pos=0.2] {$e(t)$} node[coordinate] (mm) {}  (ii);
       \draw[->] (gain) -- node[above, near end] {$u(t)$} (output);
       \draw[->] (feedback) -- node[left, near start] {$y(t)$} node[right, pos=0.95] {-} (sum);
       \draw[->, color=ppc] (mm) |- (pp) -| node[right,] {$u_P(t)$} (sum2);
       \draw[->, color=ddc] (mm) |- (dd) -| node[right,] {$u_D(t)$} (sum2);
       \draw[->, color=iic] (ii)  -- node[above,] {$u_I(t)$} (sum2);
       \draw[->] (sum2) -- node[above, near end] {} (gain);

     \end{tikzpicture}
   \end{center}
   #+end_export

   *ISA*
   \begin{align*}
   u(t) &= k_c\Big( \textcolor{ppc}{e(t)} + \textcolor{iic}{\frac{1}{\tau_i} \int_0^{t} e(\xi) d\xi} + \textcolor{ddc}{\tau_d \frac{d}{dt} e(t)} \Big)
   \end{align*}

   *Paralela*
   \begin{align*}
   u(t) &=  \textcolor{ppc}{K_p e(t)} + \textcolor{iic}{K_i \int_0^{t} e(\xi) d\xi} + \textcolor{ddc}{K_d \frac{d}{dt} e(t)}
   \end{align*}

** Controlador PID
   #+begin_export latex
   \begin{center}
     \begin{tikzpicture}[node distance=22mm, block/.style={rectangle, draw, minimum width=15mm}, sumnode/.style={circle, draw, inner sep=2pt},scale=0.8, every node/.style={scale=0.8}]
    
       \node[coordinate] (input) {};
       \node[sumnode, right of=input, node distance=16mm] (sum) {\tiny $\Sigma$};
       \node[block, right of=sum, node distance=20mm] (pid)  {\textcolor{ppc}{P}\textcolor{iic}{I}\textcolor{ddc}{D}};
       \node[coordinate, below of=sum, node distance=12mm] (feedback) {};
       \node[coordinate, right of=pid, node distance=20mm] (output) {};

       \draw[->] (input) -- node[above, pos=0.3] {$r(t)$} (sum);
       \draw[->] (sum) -- node[above] {$e(t)$} (pid);
       \draw[->] (pid) -- node[above, near end] {$u(t)$} (output);
       \draw[->] (feedback) -- node[left, near start] {$y(t)$} node[right, pos=0.95] {-} (sum);

       \begin{scope}[yshift=-3cm]
       \foreach \pos/\clr/\nme in {0/ppc/P, 2/iic/I, 4/ddc/D} {
       \node (knob) at (\pos,0) {\includegraphics[width=12mm]{../figures/knob.png}};
       \node[above of=knob, node distance=10mm] {\large \textcolor{\clr}{\nme}};
       }
       \end{scope}

       \end{tikzpicture}
   \end{center}

   #+end_export

   #+beamer: \pause

   #+begin_export latex
   \begin{tabular}{lll}
   \textbf{\textcolor{ppc}{P}} & Proporcional: & Modifica la velocidad del sistema de control\\
   \textbf{\textcolor{iic}{I}} & Integral: & Elimina el error $e(t)$ en estado estable\\
   \textbf{\textcolor{ddc}{D}} & Derivativa: & Mejora la amortiguación
   \end{tabular}
   #+end_export

** Controlador PID - efecto de las ganancias

Dado un sistema controlado por un PID \( U(s)=(K_P+K_I \frac{1}{s}+K_D s) E(s)\)
*** Graphics
:PROPERTIES:
:BEAMER_col: 0.7
:END:

    \begin{center}
 \includegraphics[width=0.48\linewidth]{../figures/fig930115-1a-1}
 \includegraphics[width=0.48\linewidth]{../figures/fig930115-1a-2}\\
 \includegraphics[width=0.48\linewidth]{../figures/fig930115-1a-3}
 \includegraphics[width=0.48\linewidth]{../figures/fig930115-1a-4}
    \end{center}
*** Text
:PROPERTIES:
:BEAMER_col: 0.3
:END:

Encuentra la respuesta del sistema en lazo cerrado para cada de los siguientes casos

   | Caso | \textcolor{ppc}{\(K_P\)} | \textcolor{iic}{\(K_I\)} | \textcolor{ddc}{\(K_D\)} |
   |------+--------------------------+--------------------------+--------------------------|
   | i)   |                        1 |                        0 |                        0 |
   | ii)  |                        1 |                        1 |                        0 |
   | iii) |                        1 |                        0 |                        1 |
   | iv)  |                        1 |                        1 |                        1 |


** Controlador PID - ajustar las ganancias
*** Graphics
    :PROPERTIES:
    :BEAMER_col: 0.6
    :END:
    #+begin_center
    \includegraphics[width=0.99\linewidth]{../figures/stepresponse-secondorder-exercise}
    #+end_center

*** Text
    :PROPERTIES:
    :BEAMER_col: 0.4
    :END:
    
   *Actividad* Cómo ajustar las ganancias \(K_P\), \(K_I\) y \(K_D\) para obtener una respuesta mejor?

   | Caso | \textcolor{ppc}{\(K_P\)} | \textcolor{iic}{\(K_I\)} | \textcolor{ddc}{\(K_D\)} |
   |------+---------------------+--------------------+--------------------|
   | A    |                     |                    |                    |
   | B    |                     |                    |                    |
   | C    |                     |                    |                    |
   | D    |                     |                    |                    |
   |------+---------------------+--------------------+--------------------|
   
* PID tuning - (Smith and Corripio) Ziegler Nichols
** Sintonización de controladores PID

*Hay varios métodos.* Entre otros:

- Ziegler & Nichols método en lazo abierto,  y método en lazo cerrado
- Smith & Corripio (usando tabla de Ziegler & Nichols)
- Cohen & Coon (como Smith & Corripio, pero otros valores en la tabla)
- Simple Internal Model Control (SIMC) 

** Método de Smith & Corripio con tabla de Ziegler & Nichols

\small

Dado modelo \[ G(s) = K \frac{\mathrm{e}^{-s\theta}}{\tau s + 1}, \] y controlador PID en forma
   \[ F(s) = k_c\left( 1 + \frac{1}{\tau_i s} + \tau_d s\right). \]

Elige los parámetros PID según la tabla siguiente (Ziegler & Nichols, 1943)
   #+begin_export latex
      \begin{center}
      \setlength{\tabcolsep}{20pt}
      \renewcommand{\arraystretch}{1.5}
      \begin{tabular}{llll}
      Controller & \(k_c\) & \(\tau_i\) & \(\tau_d\)\\
     \hline\hline
     P & \(\frac{\tau}{\theta K}\) &  & \\
     PI & \(\frac{0.9\tau}{\theta K}\) & \(\frac{\theta}{0.3}\) & \\
     PID & \(\frac{1.2\tau}{\theta K}\) & \(2\theta\) & \(\frac{\theta}{2}\)\\
     \hline
   \end{tabular}
   \end{center}

   #+end_export

   Restricción: \[0.1 < \frac{\theta}{\tau} < 0.6.\]


** Método de Cohen & Coon

\small

Dado modelo \[ G(s) = K \frac{\mathrm{e}^{-s\theta}}{\tau s + 1}, \]
elige los parámetros PID según la tabla siguiente (Cohen & Coon, 1953)
   #+begin_export latex
      \begin{center}
      \setlength{\tabcolsep}{20pt}
      \renewcommand{\arraystretch}{1.5}
      \begin{tabular}{llll}
      Controller & \(k_c\) & \(\tau_i\) & \(\tau_d\)\\
     \hline\hline
     P & \(\Big(1.03 + 0.35\big(\frac{\theta}{\tau}\big)\Big)\frac{\tau}{\theta K}\) &  & \\
     PI &  \(\Big(0.9 + 0.083\big(\frac{\theta}{\tau}\big)\Big)\frac{\tau}{\theta K}\) & \(\frac{\theta\Big(0.9 + 0.083\big(\frac{\theta}{\tau}\big)\Big)}{\Big(1.27 + 0.6\big(\frac{\theta}{\tau}\big)\Big)}\) & \\
     PID &  \(\Big(1.35 + 0.25\big(\frac{\theta}{\tau}\big)\Big)\frac{\tau}{\theta K}\) &  \(\frac{\theta\Big(1.35 + 0.25\big(\frac{\theta}{\tau}\big)\Big)}{\Big(0.54 + 0.33\big(\frac{\theta}{\tau}\big)\Big)}\) & \(\frac{\theta}{2\Big(1.35 + 0.25\big(\frac{\theta}{\tau}\big)\Big)}\)\\
     \hline
   \end{tabular}
   \end{center}

   #+end_export

* Digital logic

* Automation
** Automatización
** Automatización de un sistema neumático

*** Graphics
:PROPERTIES:
:BEAMER_col: 0.3
:END:

    \begin{center}
     \includegraphics[width=1.0\linewidth]{../figures/fluidsim-32-solenoid-cylinder.png}
    \end{center}
*** Text
:PROPERTIES:
:BEAMER_col: 0.6
:END:

#+beamer: \pause

En la automatización de una prensa se requiere un pulsador para accionar un cilindro de simple efecto que permita sujetar una pieza metálica hasta que otro pulsador active el regreso del cilindro, liberando la pieza.

** Automatizción de un sistema neumático
*** Graphics
:PROPERTIES:
:BEAMER_col: 0.6
:END:
Diagrama de escalera
    \begin{center}
                     \begin{tikzpicture}[circuit plc ladder,]
                       \node at (1, -0.3) {?};
                       \node at (1, 0.2) {A};
                       \node at (3, -0.3) {?};
                       \node at (3, 0.2) {B};
                       \node at (1, -2) {?};
                       \node at (1, -1.5) {C};

                       \draw (0,0) to[short, o-]  (0,-4.5);
                       \draw (6,0) to[short, o-](6,-4.5);
                       \draw (0,-0.3) to[short, -o] (0.8, -0.3) (1.2, -0.3) to[short, o-]  (2,-0.3)
                        (2, -0.3) to[short, -o] (2.8, -0.3)
                        (3.2, -0.3) to[short, o-,] (4,-0.3) to[short] (4,-0.3) \coil{$K_1$};
                       \draw (0,-2) to[short, -o,] (0.8, -2)
                             (1.2, -2) to[short, o-,] (2,-2)  to[short] (2,-0.3);

                       \draw (0, -3.5) to[contact NO={info={$K_1$}},] (2, -3.5) to[short] (4, -3.5) \coil{Cylinder};
                     \end{tikzpicture}
    \end{center}
*** Text
:PROPERTIES:
:BEAMER_col: 0.4
:END:

#+beamer: \pause

Elementos de control

1. Pulsador NA
2. Pulsador NC
3. Contacto NA
4. Contacto NC

Respuestas alternativas

1. A -- 1, B -- 2, C -- 3
2. A -- 2, B -- 4, C -- 3
3. A -- 1, B -- 2, C -- 4

** ¡Suerte! 

   #+begin_export latex
\Huge Lykke til!
   #+end_export
