#+OPTIONS: toc:nil
#+LaTeX_CLASS: koma-article 

# #+LATEX_CLASS: beamer
# #+LATEX_CLASS_OPTIONS: [presentation,aspectratio=1610]
# #+OPTIONS: H:2

#+LaTex_HEADER: \usepackage{khpreamble}
#+LaTex_HEADER: \usepackage{pgfplots}
#+LaTex_HEADER: \usepackage{pdfpages}
#+LaTex_HEADER: \usepackage{circuitikz}
#+LaTex_HEADER: \usepgfplotslibrary{groupplots}
#+LaTex_HEADER: \usetikzlibrary{positioning}
#+LaTex_HEADER: \renewcommand*{\not}[1]{\ensuremath{\bar{#1}}}
#+LaTex_HEADER: \renewcommand*{\not}[1]{\ensuremath{\overline{#1}}}

#+title: Course intro and circuits intro
#+date: 2020-02-12

* What do I want the students to understand?			   :noexport:
  - Course objectives
  - Course structure
  - Current and voltage
  - Resistors in series and in parallel
  - Working with a multimeter
  - Working with a DC power supply


* Which activities will the students do? 			   :noexport:
  - Practice 1, instructions on Canvas

* Course intro

** Who am I
   
** What the course is about
   - Lab, so hands on work. Both analysis, implementation and experimentation. Simulation included.
   - Circuits. Props: breadboard, multimeter, power supply, function generator, oscilloscope
     - Basic,  but interesting electrical circuits. Dynamical properties.
     - Learn to use multimeter, power supply, function generator, oscilloscope
   - Pneumatic systems. Props: tank, cylinders, valves
     - Tank system, PID control
     - Pneumatic cylinders, valves
   - PLC
     - Used in industry to control processes.

** Study guide
   - Hand out
   - Go through.
     - Emphasize objective
     - Go through plan

** Groups 
   - Form four groups

* Circuit intro

** Get the material

** Present the lab instructions

** Circuit and physical implementation

#+BEGIN_CENTER 
 \includegraphics[width=0.4\linewidth]{../../figures/R-circuit}
Draw breadboard with resistor. Connect!
#+END_CENTER

Describe the ideal voltage source: Will provide any current that the circuit may demand, at a perfectly constant voltage $u$. 
 
** Important relationsships

*** Ohm's law
    \(u = Ri\)

*** Kirchoff's current law

*** Kirchoff's voltage law

** Series connection
#+BEGIN_CENTER 
 \includegraphics[width=0.4\linewidth]{../../figures/voltage-divider-circuit}
#+END_CENTER
In the equivalent circuit with a single resistor $R_3$, then clearly $u_3=u$. And for the original circuit $u = u_1 + u_2$. The same current $i$ flows through all the elements, so from Ohm's law $u_k = R_k i_k$, we get
\( u_3 = u_1 + u_2\) and
\[ R_3 i = R_1 i + R_2 i = (R_1 + R_2) i \]
\[ R_3 = R_1 + R_2\]

This means that $i = \frac{u}{R_1 + R_2}$. So what is the voltage over $R_2$?
\[ u_2 = R_2 i = u \frac{R_2}{R_1 + R_2}. \]

** Parallel connection

#+BEGIN_CENTER 
 \includegraphics[width=0.4\linewidth]{../../figures/parallel-circuit}
#+END_CENTER

In an equivalent circuit with only one resistor $R_3$, we must have \(u_3 = u = R_3 i_0\), which implies \(i_0 = \frac{u}{R_3}\).
For the two resistors in the circuit, we have \(u_1 = u = R_1 i_1\) and \(u_2 = u = R_1 i_1\), which gives \[i_1 = \frac{u}{R_1} \qquad \text{and} \qquad \(i_2 = \frac{u}{R_2}\]
From Kirchoff's current law \(i_0 = i_1 + i_2\), so  we get
\[ \frac{u}{R_3} = \frac{u}{R_1} + \frac{u}{R_2} = u \left( \frac{1}{R_1} + \frac{1}{R_2}\right)\]
hence
\[ \frac{1}{R_3} =  \frac{1}{R_1} + \frac{1}{R_2}\]
The reciprocal \(\frac{1}{R}\) of a resistance is called \emph{admittance}. 

** Safety instructions

*** Connect everything first, then turn on the power supply

*** Use low voltage, 5V
