#+OPTIONS: toc:nil
#+LaTeX_CLASS: koma-article 

# #+LATEX_CLASS: beamer
# #+LATEX_CLASS_OPTIONS: [presentation,aspectratio=1610]
# #+OPTIONS: H:2

#+LaTex_HEADER: \usepackage{khpreamble}
#+LaTex_HEADER: \usepackage{pgfplots}
#+LaTex_HEADER: \usepackage{pdfpages}
#+LaTex_HEADER: \usepackage{circuitikz}
#+LaTex_HEADER: \usepgfplotslibrary{groupplots}
#+LaTex_HEADER: \usetikzlibrary{positioning}
#+LaTex_HEADER: \renewcommand*{\not}[1]{\ensuremath{\bar{#1}}}
#+LaTex_HEADER: \renewcommand*{\not}[1]{\ensuremath{\overline{#1}}}

#+title: Course intro and circuits intro
#+date: 2020-02-12

* What do I want the students to understand?			   :noexport:
  - Course objectives
  - Course structure
  - Current and voltage
  - Resistors in series and in parallel
  - Working with a multimeter
  - Working with a DC power supply


* Which activities will the students do? 			   :noexport:
  - Practice 1, instructions on Canvas

* Course intro

** Who am I
   
** What the course is about
   - Lab, so hands on work. Both analysis, implementation and experimentation. Simulation included.
   - Circuits. Props: breadboard, multimeter, power supply, function generator, oscilloscope
     - Basic,  but interesting electrical circuits. Dynamical properties.
     - Learn to use multimeter, power supply, function generator, oscilloscope
   - Pneumatic systems. Props: tank, cylinders, valves
     - Tank system, PID control
     - Pneumatic cylinders, valves
   - PLC
     - Used in industry to control processes.

** Study guide
   - Hand out
   - Go through.
     - Emphasize objective
     - Go through plan

** Groups 
   - Form four groups (3+3+3+2)

* Circuit intro

** Get the material

** Circuit and physical implementation

#+BEGIN_CENTER 
 \includegraphics[width=0.4\linewidth]{../../figures/R-circuit}
Draw breadboard with resistor. Connect!
#+END_CENTER

** Series connection
#+BEGIN_CENTER 
 \includegraphics[width=0.4\linewidth]{../../figures/voltage-divider-circuit}
#+END_CENTER


** Parallel connection




*** Sequence
     :PROPERTIES:
     :BEAMER_col: 0.6
     :END:      

  \begin{tikzpicture}
    \begin{groupplot} [
      group style={
        group name=timeplot,
        group size=1 by 3,
        xlabels at=all,
        horizontal sep=1cm,
        vertical sep=1cm,
      }, 
      clip=false,
      height=3cm, width=8cm,
      axis line style={->},
      axis lines=left,
      xlabel={time },
      ylabel={},
      ytick={0,1},
      xtick={0,1,2,3,4},
      % grid=both,
      % xtick=\empty,
      % ytick=\XNOLL,
      % yticklabel=$x_0$,
      ]
      \nextgroupplot [ylabel={$x_A$},]
      \addplot[red, no marks,ultra thick,] coordinates {(0,0) (1,1) (2, 1) (3,1) (4, 0)};
      \nextgroupplot [ylabel={$x_B$},]
      \addplot[red, no marks,ultra thick,] coordinates {(0,0) (1,0) (2, 1) (3,0) (4, 0)};
      \nextgroupplot [ylabel={$x_P$},]
      \addplot[red, no marks,ultra thick,] coordinates {(0,0) (1,0) (2, 1) (3,1) (4, 0)};
    \end{groupplot}
  \end{tikzpicture}

** Simplified truth table					   :noexport:
  Complete the truthtable below, which defines the control law (only states actually visited in the sequence included in the table) 
  \begin{center}
    \begin{tabular}{|ccc|cccc|}
      \hline
      $x_A$ & $x_B$ & $x_P$ & $u_A+$ & $u_A-$ & $u_B+$ & $u_B-$\\
      \hline\hline
      0 & 0 & 0 &  &  &  & \\
      1 & 0 & 0 &  &  &  & \\
      1 & 0 & 1 &  &  &  & \\
      1 & 1 & 1 &  &  &  & \\
      \hline
\end{tabular}
\end{center}

** Simplified truth table 
  Complete the truthtable below, which defines the control law (only states actually visited in the sequence included in the table) 
  \begin{center}
    \begin{tabular}{|ccc|cccc|}
      \hline
      $x_A$ & $x_B$ & $x_P$ & $u_A+$ & $u_A-$ & $u_B+$ & $u_B-$\\
      \hline\hline
      0 & 0 & 0 & 1 & 0 & 0 & 0\\
      1 & 0 & 0 & 0 & 0 & 1 & 0\\
      1 & 0 & 1 & 0 & 1 & 0 & 0 \\
      1 & 1 & 1 & 0 & 0 & 0 & 1 \\
      \hline
\end{tabular}
\end{center}
Write the boolen expression corresponding to the truth table, ignoring the posibility that the system is in any other state than the four states of the sequence. Draw circuit diagram and implement. Hint: Use only one proximity sensor per cylinder to determine the state of the cylinder. 
** Simplified truth table 
  Complete the truthtable below, which defines the control law (only states actually visited in the sequence included in the table) 
  \begin{center}
    \begin{tabular}{|ccc|cccc|}
      \hline
      $x_A$ & $x_B$ & $x_P$ & $u_A+$ & $u_A-$ & $u_B+$ & $u_B-$\\
      \hline\hline
      0 & 0 & 0 & 1 & 0 & 0 & 0\\
      1 & 0 & 0 & 0 & 0 & 1 & 0\\
      1 & 0 & 1 & 0 & 1 & 0 & 0 \\
      1 & 1 & 1 & 0 & 0 & 0 & 1 \\
      \hline
\end{tabular}
\end{center}
\begin{align*}
u_A+ &= \\
u_A- &= \\
u_B+ &= \\
u_B- &= 
 \end{align*}
** Simplified truth table 
  Complete the truthtable below, which defines the control law (only states actually visited in the sequence included in the table) 
  \begin{center}
    \begin{tabular}{|ccc|cccc|}
      \hline
      $x_A$ & $x_B$ & $x_P$ & $u_A+$ & $u_A-$ & $u_B+$ & $u_B-$\\
      \hline\hline
      0 & 0 & 0 & 1 & 0 & 0 & 0\\
      1 & 0 & 0 & 0 & 0 & 1 & 0\\
      1 & 0 & 1 & 0 & 1 & 0 & 0 \\
      1 & 1 & 1 & 0 & 0 & 0 & 1 \\
      \hline
\end{tabular}
\end{center}
\begin{align*}
u_A+ &= \not{x_A}\\
u_A- &= x_A\not{x_B}x_P\\
u_B+ &= x_A\not{x_B}\not{x_P}\\
u_B- &= x_B
 \end{align*}

** Implementing the sequence A+B+B-A-,  circuit diagram
   Assuming existence of latching circuit for $x_P$. Proximity sensors providing $\not{x_a}$ (A retracted) and $x_B$ (B extended).

*** Control law
    :PROPERTIES:
    :BEAMER_col: 0.25
    :BEAMER_env: block
    :END:      
     \begin{align*}
       u_A+ &= \not{x_A}\\
       u_A- &= x_A\not{x_B}x_P\\
       u_B+ &= x_A\not{x_B}\not{x_P}\\
       u_B- &= x_B
     \end{align*}
       
*** Control law
    :PROPERTIES:
    :BEAMER_col: 0.75
    :END:      
  
   #+BEGIN_LaTeX
       \begin{center}
                \begin{tikzpicture}
                  \node at (0,0.5) {+24V};
                  \node at (9,0.5) {0V};
                  \draw (0,0) to[short, o-]  (0,-6);
                  \draw (9,0) to[short, o-](9,-6);
                  \draw (0,-0.3) to[switch, *-, label=$\not{x_A}$] (4,-0.3) to[short] (7,-0.3) to[twoport, label=$u_A+$, -*] (9,-0.3);
                  \draw (0,-2) to[opening switch, *-, label=$\not{x_A}$] (2,-2)  to[ opening switch, label=$x_B$] (4,-2) to [switch, label=$x_P$] (6,-2) to[short] (7,-2) to[twoport, label=$u_A-$, -*] (9,-2);
                  \draw (0,-3.7) to[opening switch, *-, label=$\not{x_A}$] (2,-3.7)  to[opening switch, label=$x_B$] (4,-3.7) to [opening switch, label=$x_P$] (6,-3.7) to[short] (7,-3.7) to[twoport, label=$u_B+$, -*] (9,-3.7);
                  \draw (0,-5.4) to[switch, *-, label=$x_B$] (2,-5.4) to[short] (7,-5.4) to[twoport, label=$u_B-$, -*] (9,-5.4);
                \end{tikzpicture}
       \end{center}
#+END_LaTeX
    
** Implementing the sequence A+B+B-A-, relays

       
*** Control law
    :PROPERTIES:
    :BEAMER_col: 0.75
    :END:      
  
   #+BEGIN_LaTeX
       \begin{center}
                \begin{tikzpicture}
                  \node at (0,0.5) {+24V};
                  \node at (9,0.5) {0V};
                  \draw (0,0) to[short, o-]  (0,-7);
                  \draw (9,0) to[short, o-](9,-7);
                  %latch
                  \draw (0,-0.3) to[switch, *-, label=$x_B$] (2,-0.3) to [opening switch, label=$\not{x_A}$] (4,-0.3) to[short] (7,-0.3) to[twoport, label=$x_P$, -*] (9,-0.3);
                  \draw (0,-2) to[switch, *-, label=$x_P$] (2,-2)  to[short] (2,-0.3);
                  \draw (0,-3.2) to[short, *-] (1,-3.2) to[twoport, label=A retracted] (7,-3.2) to[short,-*] (9,-3.2);
                  \draw (4., -3.55) to[short] (4., -4.6) to[twoport, label=$\not{x_A}$, -*] (9,-4.6);
                  \draw (0,-5.3) to[twoport, label=B extended,*-] (3,-5.3) to[short,-*] (9,-5.3);
                  \draw (1.5, -5.65) to[short] (1.5, -6.6) to[twoport, label=$x_B$, -*] (9,-6.6);

                \end{tikzpicture}
       \end{center}
#+END_LaTeX
    

* PLC
** The Siemens S7 series PLC
#+BEGIN_CENTER 
 \includegraphics[width=0.8\linewidth]{../figures/s7-1500.jpeg}
#+END_CENTER

#+BEGIN_LaTeX
{\footnotesize From Siemens}
#+END_LaTeX


** Programming
   Three ways to program the Siemens s7 series
   1. *Ladder diagram (LAD)*
   2. Function Block Diagram (FBD)
   3. Structured Control Language (SCL)

** Execution
#+BEGIN_CENTER 
 \includegraphics[width=0.7\linewidth]{../figures/plc-scan.png}
#+END_CENTER
* Ladder diagrams
#+BEGIN_LaTeX
\def\ladderend{12}
\def\relayr{0.4}
#+END_LaTeX
** Ladder diagrams
   Equivalent to circuit diagram for control logic using relays

** Basics
   #+BEGIN_LaTeX
       \begin{center}
       \begin{circuitikz}
         \node at (0,0.5) {(+24 V)};
         \draw[thick] (0,0) to[short,o-] (0,-2);
         \draw[thick] (0,-1) to[short,*-]  (\ladderend,-1) (\ladderend,-0.6) to[short] (\ladderend,-1.4);
         \node[anchor=west] at (\ladderend.5,-1) {(0 V)};
         \node[coordinate, pin=40:{rung}] at (5,-1) {};
       \end{circuitikz}
       \end{center}
   #+END_LaTeX
** Basics --- Pushbutton activating an output

   #+BEGIN_LaTeX
       \begin{center}
       \begin{circuitikz}
         \ctikzset{bipoles/thickness=1, bipoles/capacitor/height=0.4}
         \draw[thick] (0,0) to[short,o-] (0,-2);
         \draw[thick] (0,-1) to[C=I0.0, PB1,*-] (4, -1) to[short] (8,-1) arc (180:110:\relayr) (8,-1) arc (180:250:\relayr) (9,-1) arc (0:70:\relayr) (9,-1) arc (0:-70:\relayr) (9,-1) to[short] (\ladderend, -1) (\ladderend,-0.6) to[short] (\ladderend,-1.4);
         \node at (8.5, -0.4) {Q0.1};
       \end{circuitikz}
       \end{center}
   #+END_LaTeX

** Basics --- Latching circuit


   #+BEGIN_LaTeX
       \begin{center}
       \begin{circuitikz}
         \ctikzset{bipoles/thickness=1, bipoles/capacitor/height=0.4}
         \draw[thick] (0,0) to[short,o-] (0,-3.3);
         \draw[thick] (0,-1) to[C=I0.0,*-] (3, -1) to[C=I0.1, ] (6,-1) to[short,] (9,-1) arc (180:110:\relayr) (9,-1) arc (180:250:\relayr) (10,-1) arc (0:70:\relayr) (10,-1) arc (0:-70:\relayr) (10,-1) to[short] (\ladderend, -1) (\ladderend,-0.6) to[short] (\ladderend,-1.4);
         \node at (9.5, -0.4) {Q0.0};
         \draw[thin] (4.4, -1.2) -- (4.6, -0.8); 
         \draw[thick] (0,-3) to[C, l_=Q0.0, *-] (3,-3) to[short] (3,-1);
       \end{circuitikz}
       \end{center}
   #+END_LaTeX

** Timer
#+BEGIN_CENTER 
 \includegraphics[width=\linewidth]{../figures/plc-TON-operation.png}
#+END_CENTER

** Timer example, PT=2

\includegraphics[width=0.6\linewidth]{../figures/plc-TON-operation.png}

#+BEGIN_LaTeX
  \begin{center}
  \begin{tikzpicture}
      \begin{groupplot} [
        group style={
          group name=timeplot,
          group size=1 by 3,
          xlabels at=edge bottom,
          horizontal sep=1cm,
          vertical sep=6mm,
        }, 
        clip=false,
        height=2.5cm, width=10cm,
        axis line style={->},
        axis lines=left,
        xlabel={time },
        ylabel={},
        ytick=\empty,
        xtick=\empty,
        xmin=0, xmax=10,
        ymin=0, ymax=1.2,
        % grid=both,
        % xtick=\empty,
        % ytick=\XNOLL,
        % yticklabel=$x_0$,
        ]
        \nextgroupplot [ylabel={IN}, xtick={1,2,4,8},]
        \addplot[ red, no marks, ultra thick,] coordinates {(0,0) (1,0) (1, 1) (2,1) (2, 0) (4, 0) (4,1) (8,1) (8,0) (10,0)};
        \nextgroupplot [ylabel={ET},ymax=3, height=4cm]
        \addplot[dashed, no marks] coordinates {(0,2) (10,2)} node[pos=0.99, pin=10:{PT=2}] {};
        \nextgroupplot [ylabel={Q}, ]
        %\addplot[ no marks,thick,] coordinates {(0,0) (1,0) (2, 1) (3,0) (4, 0)};
      \end{groupplot}
    \end{tikzpicture}
  \end{center}
    
#+END_LaTeX
** Counter
#+BEGIN_CENTER 
 \includegraphics[width=\linewidth]{../figures/plc-CTU-operation.png}
#+END_CENTER
** Counter example, PV=3
 \includegraphics[width=0.6\linewidth]{../figures/plc-CTU-operation.png}
#+BEGIN_LaTeX
  \begin{center}
  \begin{tikzpicture}
      \begin{groupplot} [
        group style={
          group name=timeplot,
          group size=1 by 4,
          xlabels at=edge bottom,
          horizontal sep=1cm,
          vertical sep=6mm,
        }, 
        clip=false,
        height=2cm, width=10cm,
        axis line style={->},
        axis lines=left,
        xlabel={time },
        ylabel={},
        ytick=\empty,
        xtick=\empty,
        xmin=0, xmax=10,
        ymin=0, ymax=1.2,
        % grid=both,
        % xtick=\empty,
        % ytick=\XNOLL,
        % yticklabel=$x_0$,
        ]
        \nextgroupplot [ylabel={CU}, ]
        \addplot[ red, no marks, ultra thick,] coordinates {(0,0) (1,0) (1, 1) (2,1) (2, 0) (3, 0) (3,1) (5,1) (5,0) (6,0) (6,1) (6.5,1) (6.5,0) (7,0) (7,1) (8,1) (8,0) (8.5,0) (8.5, 1) (9,1) (9,0) (10,0)};
        \nextgroupplot [ylabel={R}]
        \addplot[ red, no marks, ultra thick,] coordinates {(0,0) (4,0) (4, 1) (4.5,1) (4.5, 0) (10, 0)};
        \nextgroupplot [ylabel={CV},height=4cm]
        \nextgroupplot [ylabel={Q}, ]
        %\addplot[ no marks,thick,] coordinates {(0,0) (1,0) (2, 1) (3,0) (4, 0)};
      \end{groupplot}
    \end{tikzpicture}
  \end{center}
    
#+END_LaTeX


** Set output 1 high with 2s delay
   #+BEGIN_LaTeX
     \begin{center}
     \begin{circuitikz}
       \ctikzset{bipoles/thickness=1, bipoles/capacitor/height=0.4}
       % Rail
       \draw[thick] (0,0) to[short,o-] (0,-5.3);
       % Latching circuit
       \draw[thick] (0,-1) to[C=I0.0,*-] (3, -1) to[C=I0.1, ] (6,-1) to[short,] (9,-1) arc (180:110:\relayr) (9,-1) arc (180:250:\relayr) (10,-1) arc (0:70:\relayr) (10,-1) arc (0:-70:\relayr) (10,-1) to[short] (\ladderend, -1) (\ladderend,-0.6) to[short] (\ladderend,-1.4);
       \node at (9.5, -0.4) {M};
       \draw[thin] (4.4, -1.2) -- (4.6, -0.8); 
       \draw[thick] (0,-3) to[C, l_=M, *-] (3,-3) to[short] (3,-1);
       % TON
       \draw[thick] (0,-5) to[C=M,*-] (4, -5);
        
     \end{circuitikz}
     \end{center}
   #+END_LaTeX


** Set output 1 high with 2s delay
   #+BEGIN_LaTeX
     \begin{center}
     \begin{circuitikz}
       \ctikzset{bipoles/thickness=1, bipoles/capacitor/height=0.4}
       % Rail
       \draw[thick] (0,0) to[short,o-] (0,-5.3);
       % Latching circuit
       \draw[thick] (0,-1) to[C=I0.0,*-] (3, -1) to[C=I0.1, ] (6,-1) to[short,] (9,-1) arc (180:110:\relayr) (9,-1) arc (180:250:\relayr) (10,-1) arc (0:70:\relayr) (10,-1) arc (0:-70:\relayr) (10,-1) to[short] (\ladderend, -1) (\ladderend,-0.6) to[short] (\ladderend,-1.4);
       \node at (9.5, -0.4) {M};
       \draw[thin] (4.4, -1.2) -- (4.6, -0.8); 
       \draw[thick] (0,-3) to[C, l_=M, *-] (3,-3) to[short] (3,-1);
       % TON
       \draw[thick] (0,-5) to[C=M,*-] (4, -5) to[short] (7,-5) arc (180:110:\relayr) (7,-5) arc (180:250:\relayr) (8,-5) arc (0:70:\relayr) (8,-5) arc (0:-70:\relayr) (8,-5) to[short] (9,-5) arc (180:110:\relayr) (9,-5) arc (180:250:\relayr) (10,-5) arc (0:70:\relayr) (10,-5) arc (0:-70:\relayr) (10,-5) to[short] (\ladderend, -5) (\ladderend,-0.6) to[short] (\ladderend,-5.4);
       \node at (9.5, -4.4) {Q0.1};
       \node at (7.5, -5) {TON};
       \node at (7.5, -5.7) {2s};
        
     \end{circuitikz}
     \end{center}
   #+END_LaTeX


** Set output 1 high after hitting button 4 times
   #+BEGIN_LaTeX
     \begin{center}
     \begin{circuitikz}
       \ctikzset{bipoles/thickness=1, bipoles/capacitor/height=0.4}
       % Rail
       \draw[thick] (0,0) to[short,o-] (0,-2.3);
       % Button
       \draw[thick] (0,-1) to[C=I0.0,*-] (4.1, -1) ;
       \draw[thick] (\ladderend,-0.7) to[short] (\ladderend,-1.3);
     \end{circuitikz}
     \end{center}
   #+END_LaTeX

** Set output 1 high after hitting button 4 times
   #+BEGIN_LaTeX
     \begin{center}
     \begin{circuitikz}
       \ctikzset{bipoles/thickness=1, bipoles/capacitor/height=0.4}
       % Rail
       \draw[thick] (0,0) to[short,o-] (0,-2.3);
       % Button
       \draw[thick] (0,-1) to[C=I0.0,*-] (4.1, -1) ;
       \node at (5,-0.87) {\includegraphics[width=23mm]{../figures/plc-CTU.png}};
       \draw[thick] (5.9,-1)  to[short,] (9,-1) arc (180:110:\relayr) (9,-1) arc (180:250:\relayr) (10,-1) arc (0:70:\relayr) (10,-1) arc (0:-70:\relayr) (10,-1) to[short] (\ladderend, -1) (\ladderend,-0.6) to[short] (\ladderend,-1.4);
       \node at (9.5, -0.4) {Q0.1};
       \node at (3.5, -1.8) {4};
     \end{circuitikz}
     \end{center}
   #+END_LaTeX

* The assignment
** The assignment: Press the cheese several times
\begin{center}
  \begin{tikzpicture}
    \begin{groupplot} [
      group style={
        group name=timeplot,
        group size=1 by 2,
        xlabels at=edge bottom,
        horizontal sep=1cm,
        vertical sep=1cm,
      }, 
      clip=false,
      height=3.3cm, width=9.3cm,
      axis line style={->},
      axis lines=left,
      xlabel={time },
      ylabel={},
      ytick={0,1},
      %xtick={0,1,2,3,4},
      % grid=both,
      % xtick=\empty,
      % ytick=\XNOLL,
      % yticklabel=$x_0$,
      ]
      \nextgroupplot [ylabel={$x_A$},]
      \addplot[red, no marks,ultra thick,] coordinates {(0,0) (1,1) (2, 1) (12,1) (13, 0)};
      \nextgroupplot [ylabel={$x_B$},]
      \addplot[red, no marks,ultra thick,] coordinates {(0,0) (1,0) (2, 1) (3,1) (4, 0) (5,0) (6,1) (7,1) (8, 0) (9,0) (10,1) (11,1) (12,0) (13,0)};
      \draw[red, thin] (axis cs: 4,0) -- (axis cs: 4,-0.5);
      \draw[red, thin] (axis cs: 5,0) -- (axis cs: 5,-0.5);
      \draw[<->] (axis cs: 4,-0.48) -- node[below] {\unit{1}{\second}} (axis cs: 5, -0.48);
      \draw[red, thin] (axis cs: 2,1) -- (axis cs: 2,-0.5);
      \draw[red, thin] (axis cs: 3,1) -- (axis cs: 3,-0.5);
      \draw[<->] (axis cs: 2,-0.48) -- node[below] {\unit{1}{\second}} (axis cs: 3, -0.48);
    \end{groupplot}
  \end{tikzpicture}
\end{center}

** Resources
   - https://en.wikibooks.org/wiki/Introductory_PLC_Programming
   - https://euroec.by/assets/files/siemens/s71200_easy_book_en-US_en-US.pdf
